### ISSUE TITLE
指定搜索的功能

### ISSUE THREAD

**Issue by RyanOvO** [InternLM/MindSearch#101]
可以支持指定网站嘛？譬如如下场景：
1. 内网知识库网站
之类的

**Comment by liujiangning30** [comment]
DuckDuckGo supports searching content on a specific website. You can use the `site:` operator to restrict the search scope to a particular website. For example: site:example.com your search terms. Specifically, you need to target [your query](https://github.com/InternLM/lagent/blob/81e7ace8fc06a65f949fc63448928844d687cc22/lagent/actions/bing_browser.py#L77) to the desired website.

**Comment by Yue-Rain** [comment]
DuckDuckGo 搜索极大影响了项目的效果，建议针对国内用户提供对应的解决方案
