### ISSUE TITLE
streamlit报错HTTPConnectionPool Error

### ISSUE THREAD

**Issue by fyxc** [InternLM/MindSearch#102]
ReadTimeout: HTTPConnectionPool(host='localhost', port=8002): Read timed out. (read timeout=20)
Traceback:
File "C:\Users\rx\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\rx\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
File "C:\Users\rx\MindSearch\frontend\mindsearch_streamlit.py", line 319, in <module>
    main()

[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 32776.
2024-08-05 21:12:58,702 - lmdeploy - WARNING - get 227 model params
[WARNING] gemm_config.in is not found; using default GEMM algo
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
INFO:     Started server process [25572]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:23333 (Press CTRL+C to quit)

**Comment by liujiangning30** [comment]
The MindSearch service loads the model first on the first request, which can potentially cause a gradio/streamlit timeout. You can click `Clear History` or refresh the page and start from a new request.

**Comment by fyxc** [comment]
same error in streamlit, I have restarted the backend. will try other frontend options and see

C:\Users\rx\MindSearch> python -m mindsearch.app --lang en --model_format internlm_server
[32mINFO[0m:     Started server process [[36m22000[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8002[0m (Press CTRL+C to quit)
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin, please note cuda version should >= 11.3 when compiled with cuda 11
C:\Users\rx\AppData\Local\Programs\Python\Python312\Lib\site-packages\fire\core.py:59: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
C:\Users\rx\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin, please note cuda version should >= 11.3 when compiled with cuda 11
C:\Users\rx\AppData\Local\Programs\Python\Python312\Lib\site-packages\fire\core.py:59: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Fetching 20 files: 100%|███████████████████████████████████████████████████████████████████████| 20/20 [00:00<?, ?it/s]
<frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.
<frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.ScalarMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 32776.
2024-08-06 09:55:36,227 - lmdeploy - WARNING - get 227 model params
[WARNING] gemm_config.in is not found; using default GEMM algo
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
INFO:     Started server process [22620]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:23333 (Press CTRL+C to quit)
