### ISSUE TITLE
仅仅返回一个响应之后就没有响应了，llm对接的gpt-4o

### ISSUE THREAD

**Issue by boxter007** [InternLM/MindSearch#105]
{"response": {"type": "planner", "content": "", "state": 0, "actions": [], "response": "", "inner_steps": [{"role": "user", "content": "中国"}], "nodes": {}, "adjacency_list": [], "references": {}, "errmsg": null, "adj": {}}, "current_node": null}

**Comment by liujiangning30** [comment]
麻烦贴一下打印的日志
