### ISSUE TITLE
Method Not Allowed

### ISSUE THREAD

**Issue by ssrheart425** [InternLM/MindSearch#106]
修改了openai.py中的OPENAI_API_BASE，models中的key，报错DeprecationWarning: `top_k` parameter is deprecated in OpenAI APIs.下面是终端报错信息，```(mindsearch) PS D:\MindSearch-main> python -m mindsearch.app --lang cn --model_format gpt4
INFO:     Started server process [21808]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8002 (Press CTRL+C to quit)
INFO:     127.0.0.1:13032 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:13032 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:13032 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:13032 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:13070 - "POST /solve HTTP/1.1" 200 OK
D:\pyEnvs\mindsearch\lib\site-packages\lagent\llms\openai.py:397: DeprecationWarning: `top_k` parameter is deprecated in OpenAI APIs.
  warnings.warn(
{"detail":"Method Not Allowed"}

ERROR:root:Exception in sync_generator_wrapper: Operation on the closed queue is forbidden
Traceback (most recent call last):
  File "D:\MindSearch-main\mindsearch\app.py", line 69, in sync_generator_wrapper
    queue.sync_q.put(response)
  File "D:\pyEnvs\mindsearch\lib\site-packages\janus\__init__.py", line 371, in put
    self._parent._check_closing()
  File "D:\pyEnvs\mindsearch\lib\site-packages\janus\__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=RuntimeError('Operation on the closed queue is forbidden')>
Traceback (most recent call last):
  File "D:\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\MindSearch-main\mindsearch\app.py", line 75, in sync_generator_wrapper
RuntimeError: Operation on the closed queue is forbidden
INFO:     127.0.0.1:13140 - "POST /solve HTTP/1.1" 200 OK
{"detail":"Method Not Allowed"}
```

**Comment by ssrheart425** [comment]
`gpt4 = dict(type=GPTAPI,
            model_type='gpt-4o',
            key=os.environ.get('OPENAI_API_KEY', 'sk-KIkMP5glEOo2QF0V1D4gTQ'))` 这是我models中的配置

**Comment by ssrheart425** [comment]
`gpt4 = dict(type=GPTAPI,
            model_type='gpt-4o',
            key=os.environ.get('OPENAI_API_KEY', 'sk-KIk**************TQ'))` 这是我models中的配置

**Comment by liujiangning30** [comment]
OPENAI_API_BASE不需要改，实测gpt-4o没问题。

**Comment by ssrheart425** [comment]
我这边是需要修改openai_api_base的，因为使用的是litellm，有好的解决办法吗
