### ISSUE TITLE
Google API

### ISSUE THREAD

**Issue by VersaceXcodes** [InternLM/MindSearch#109]
How to use Google API instead of Bing API?

**Comment by Harold-lkk** [comment]
Reference
https://github.com/InternLM/lagent/blob/a8ae3872fac6e23f832d860131a1196f1a722fe1/lagent/actions/bing_browser.py#L20

modify https://github.com/InternLM/lagent/blob/a8ae3872fac6e23f832d860131a1196f1a722fe1/lagent/actions/google_search.py#L124
to a `GoogleSearch` and change search type https://github.com/InternLM/MindSearch/blob/b3667655a53b11ad35660b5f275bcc6addb2586c/mindsearch/agent/__init__.py#L46

**Comment by VersaceXcodes** [comment]
do I still need to use bing api key? considering it will still be using bing browser as you set above?

**Comment by liujiangning30** [comment]
You still need to use serper google api key. You can create a free API key at `https://serper.dev`
