### ISSUE TITLE
多次遇到输出一半停止

### ISSUE THREAD

**Issue by ye8303019** [InternLM/MindSearch#111]
![image](https://github.com/user-attachments/assets/5c28c6d1-fbf4-4f40-a4c8-7c1f3d9e7adc)
![image](https://github.com/user-attachments/assets/dd6b3f62-5bdc-4660-8d8b-37d6bf261e08)
![image](https://github.com/user-attachments/assets/e30e343f-4ea3-43ee-9224-f39bf141f489)

如上图所示，Streamlit
启动命令：
python -m mindsearch.app --lang cn --model_format gpt4

**Comment by liujiangning30** [comment]
你可以通过max_new_tokens更改最大输出长度，默认应该是4096，如下：
```
gpt4 = dict(type=GPTAPI,
            model_type='gpt-4-turbo',
            key=os.environ.get('OPENAI_API_KEY', 'YOUR OPENAI API KEY'),
            max_new_tokens=8192)
```

**Comment by ye8303019** [comment]
谢谢，已解决
