### ISSUE TITLE
Errors from React frontend

### ISSUE THREAD

**Issue by MyraBaba** [InternLM/MindSearch#113]
Hi, 

can we use serper or bing search ?

also can we tell the search agent minimum retrieved content count to increase details ?

I am getting these errors always and the final summary cant be generated : 

> 
> 
> ERROR:mindsearch.agent.mindsearch_agent:Error in model_stream_thread: 'content'
> Traceback (most recent call last):
>   File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 148, in model_stream_thread
>     for answer in agent.stream_chat(
>   File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 46, in stream_chat
>     for agent_return in super().stream_chat(message,
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/agents/internlm2_agent.py", line 303, in stream_chat
>     for model_state, res, _ in self._llm.stream_chat(prompt, **kwargs):
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 151, in stream_chat
>     for text in self._stream_chat(messages, **gen_params):
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 288, in streaming
>     yield choice['delta']['content']
> KeyError: 'content'
> ____________________________________
> 
> 
> 
> INFO:httpx:HTTP Request: POST https://duckduckgo.com "HTTP/2 200 OK"
> 
>     response = await connection.handle_async_request(
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
>     raise exc
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
>     stream = await self._connect(request)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 154, in _connect
>     stream = await stream.start_tls(**kwargs)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 68, in start_tls
>     with map_exceptions(exc_map):
>   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.ConnectTimeout
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 117, in _aget_url
>     resp = await self._aclient.request(method, url, content=content, data=data, params=params)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
>     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
>     response = await self._send_handling_auth(
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
>     response = await self._send_handling_redirects(
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
>     response = await self._send_single_request(request)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
>     response = await transport.handle_async_request(request)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
>     with map_httpcore_exceptions():
>   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
> 
> s
>     raise mapped_exc(message) from exc
> httpx.ConnectTimeout
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/actions/bing_browser.py", line 62, in search
>     response = self._call_ddgs(
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/actions/bing_browser.py", line 77, in _call_ddgs
>     response = ddgs.text(query.strip("'"), max_results=10)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 57, in text
>     return self._run_async_in_thread(super().text(*args, **kwargs))
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 53, in _run_async_in_thread
>     result = future.result()
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
>     return self.__get_result()
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
>     raise self._exception
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 171, in text
>     results = await self._text_api(keywords, region, safesearch, timelimit, max_results)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 262, in _text_api
>     raise e
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 257, in _text_api
>     await asyncio.gather(*tasks)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 233, in _text_api_page
>     resp_content = await self._aget_url("GET", "https://links.duckduckgo.com/d.js", params=payload)
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 120, in _aget_url
>     raise TimeoutException(f"{url} {type(ex).__name__}: {ex}") from ex
> duckduckgo_search.exceptions.TimeoutException: https://links.duckduckgo.com/d.js ConnectTimeout:
> INFO:httpx:HTTP Request: POST https://duckduckgo.com "HTTP/2 200 OK"
> INFO:httpx:HTTP Request: GET https://links.duckduckgo.com/d.js?q=T%C3%BCrkiye%20Instagram%20yasa%C4%9F%C4%B1%202024%20A%C4%9Fustos%20h%C3%BCk%C3%BCmet%20a%C3%A7%C4%B1klamalar%C4%B1&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-85185288614281050648711568312041807720&ex=-1 "HTTP/2 200 OK"
> 
> ----------------------------
> 
> 
> ERROR:mindsearch.agent.mindsearch_agent:Error in model_stream_thread: 'content'
> Traceback (most recent call last):
>   File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 148, in model_stream_thread
>     for answer in agent.stream_chat(
>   File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 46, in stream_chat
>     for agent_return in super().stream_chat(message,
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/agents/internlm2_agent.py", line 303, in stream_chat
>     for model_state, res, _ in self._llm.stream_chat(prompt, **kwargs):
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 151, in stream_chat
>     for text in self._stream_chat(messages, **gen_params):
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 288, in streaming
>     yield choice['delta']['content']
> KeyError: 'content'
> 
> -------------------------
> 
> # Add the response node
> graph.add_response_node(node_name="response", node_content=response_content)
> graph.node("response")
> ```<|action_end|>
> ERROR:mindsearch.agent.mindsearch_agent:Error executing code: WebSearchGraph.add_response_node() got an unexpected keyword argument 'node_content'
> Traceback (most recent call last):
>   File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 360, in run_command
>     exec(cmd, globals(), self.local_dict)
>   File "<string>", line 16, in <module>
> TypeError: WebSearchGraph.add_response_node() got an unexpected keyword argument 'node_content'
> Exception in thread Thread-19 (run_command):
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 360, in run_command
>     exec(cmd, globals(), self.local_dict)
>   File "<string>", line 16, in <module>
> TypeError: WebSearchGraph.add_response_node() got an unexpected keyword argument 'node_content'
> ERROR:root:Exception in sync_generator_wrapper: 'content'
> Traceback (most recent call last):
>   File "/home/bc/Projects/ODS/MindSearch/mindsearch/app.py", line 69, in sync_generator_wrapper
>     for response in agent.stream_chat(inputs):
>   File "/home/bc/Projects/ODS/MindSearch/mindsearch/agent/mindsearch_agent.py", line 214, in stream_chat
>     for model_state, response, _ in self.llm.stream_chat(
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 151, in stream_chat
>     for text in self._stream_chat(messages, **gen_params):
>   File "/home/bc/Projects/ODS/MindSearch/venvMindSearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 288, in streaming
>     yield choice['delta']['content']
> KeyError: 'content'

**Comment by liujiangning30** [comment]
1. You can switch search engines using `searcher_type` (such as BingSearch) and control the number of articles retrieved for each query with `topk`. Check [this](https://github.com/InternLM/MindSearch/blob/b3667655a53b11ad35660b5f275bcc6addb2586c/mindsearch/agent/__init__.py#L46).
2. The core reason why the final response was not generated was that the code was written incorrectly, i.e. `TypeError: WebSearchGraph.add_response_node() got an unexpected keyword argument 'node_content'`. You may need to optimize the fewshot so that it follows the response protocol.
