### ISSUE TITLE
一直在重复搜索

### ISSUE THREAD

**Issue by luyizhou6126214** [InternLM/MindSearch#116]
服务启动后，问一个问题，但是后台一直在重复搜索
![image](https://github.com/user-attachments/assets/cd7898ab-9d65-4299-9aa0-b26d894036ef)

**Comment by luyizhou6126214** [comment]
后台日志倒没有报错，只是一直在重复处理这个请求

**Comment by Maolaohei** [comment]
这个项目很吃模型。我用DeepSeek-Chat 就一直重复处理。用DeepSeek-Coder倒是能出结果，但这个结果效果非常差。
![图片](https://github.com/user-attachments/assets/3ae1ee19-7f26-4a5c-99b9-22d4eac1473f)

**Comment by liujiangning30** [comment]
sse有page visibility和中断重连的监听，如果请求过程中切页面了再回来，sse会重复请求。
