### ISSUE TITLE
可否考虑后续增加更加方便的配置文档

### ISSUE THREAD

**Issue by dvdcjw** [InternLM/MindSearch#117]
现在配置信息要自己手动该很麻烦，都在py里面，而且openai的baseurl没有直接的设置方法，必须在site-packages/lagent/llms/openai.py手动改，很麻烦。

**Comment by wangr0031** [comment]
修改mindsearch/agent/models.py里面的配置就行了，加上`openai_api_base`参数
```
gpt4 = dict(type=GPTAPI,
            model_type='gpt-4o',
            openai_api_base='http://127.0.0.1:8899/v1/chat/completions',
            key='xxxxxx')
```

**Comment by ssrheart425** [comment]
> 修改mindsearch/agent/models.py里面的配置就行了，加上`openai_api_base`参数
> 
> ```
> gpt4 = dict(type=GPTAPI,
>             model_type='gpt-4o',
>             openai_api_base='http://127.0.0.1:8899/v1/chat/completions',
>             key='xxxxxx')
> ```

麻烦看看这是什么原因，models.py与openai.py中修改了open_api_base，我是使用的litellm。
以下报错：`PS D:\MindSearch-main> python -m mindsearch.app --lang cn --model_format gpt4
INFO:     Started server process [12044]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
INFO:     127.0.0.1:3487 - "OPTIONS /solve HTTP/1.1" 200 OK
INFO:     127.0.0.1:3487 - "POST /solve HTTP/1.1" 200 OK
D:\pyEnvs\mindsearch\lib\site-packages\lagent\llms\openai.py:397: DeprecationWarning: `top_k` parameter is deprecated in OpenAI APIs.
  warnings.warn(
{"detail":"Method Not Allowed"}

INFO:     127.0.0.1:3591 - "POST /solve HTTP/1.1" 200 OK
{"detail":"Method Not Allowed"}`

**Comment by ssrheart425** [comment]
> 修改mindsearch/agent/models.py里面的配置就行了，加上`openai_api_base`参数
> 
> ```
> gpt4 = dict(type=GPTAPI,
>             model_type='gpt-4o',
>             openai_api_base='http://127.0.0.1:8899/v1/chat/completions',
>             key='xxxxxx')
> ```

麻烦看看这是什么原因，models.py与openai.py中修改了open_api_base，我是使用的litellm。
以下报错：
```
PS D:\MindSearch-main> python -m mindsearch.app --lang cn --model_format gpt4
INFO:     Started server process [12044]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
INFO:     127.0.0.1:3487 - "OPTIONS /solve HTTP/1.1" 200 OK
INFO:     127.0.0.1:3487 - "POST /solve HTTP/1.1" 200 OK
D:\pyEnvs\mindsearch\lib\site-packages\lagent\llms\openai.py:397: DeprecationWarning: `top_k` parameter is deprecated in OpenAI APIs.
  warnings.warn(
{"detail":"Method Not Allowed"}

INFO:     127.0.0.1:3591 - "POST /solve HTTP/1.1" 200 OK
{"detail":"Method Not Allowed"}
```  是我的litellm不支持吗？
以下是我models.py中的配置：
```
gpt4 = dict(
    type=GPTAPI,
    model_type="gpt-4o",
    openai_api_base="https://litellm.ag******e.ai/",
    key="sk-KIkMP**************4gTQ",
)
```

**Comment by ssrheart425** [comment]
> 修改mindsearch/agent/models.py里面的配置就行了，加上`openai_api_base`参数
> 
> ```
> gpt4 = dict(type=GPTAPI,
>             model_type='gpt-4o',
>             openai_api_base='http://127.0.0.1:8899/v1/chat/completions',
>             key='xxxxxx')
> ```

麻烦看看这是什么原因，models.py与openai.py中修改了open_api_base，我是使用的litellm。
以下报错：
```
PS D:\MindSearch-main> python -m mindsearch.app --lang cn --model_format gpt4
INFO:     Started server process [12044]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
INFO:     127.0.0.1:3487 - "OPTIONS /solve HTTP/1.1" 200 OK
INFO:     127.0.0.1:3487 - "POST /solve HTTP/1.1" 200 OK
D:\pyEnvs\mindsearch\lib\site-packages\lagent\llms\openai.py:397: DeprecationWarning: `top_k` parameter is deprecated in OpenAI APIs.
  warnings.warn(
{"detail":"Method Not Allowed"}

INFO:     127.0.0.1:3591 - "POST /solve HTTP/1.1" 200 OK
{"detail":"Method Not Allowed"}
```


我的models.py中的配置如下：
```
gpt4 = dict(
    type=GPTAPI,
    model_type="gpt-4o",
    openai_api_base="https://litellm.a**********e.ai/",
    key="sk-KIkMP*************gTQ",
)
```

是我的litellm不支持吗？非常需要你们的帮助，很想使用mindsearch，感谢。

**Comment by wangr0031** [comment]
`openai_api_base=https://litellm.a**********e.ai/v1/chat/completions` 要用这样的格式，需要保证这个接口是存在的

**Comment by ssrheart425** [comment]
> `openai_api_base=https://litellm.a**********e.ai/v1/chat/completions` 要用这样的格式，需要保证这个接口是存在的

我正常使用是可以的，以下是我的代码：
```
from openai import OpenAI

client = OpenAI(
    base_url="https://litellm.ag***************e.ai/",
    api_key="sk-K****************1D4gTQ",
)

completion = client.chat.completions.create(
    model="gpt-4o-mini", messages=[{"role": "user", "content": "你好"}]
)

print(completion)
```

这个是正常可以返回结果的

**Comment by wangr0031** [comment]
openai_api_base=https://litellm.a**********e.ai/v1/chat/completions 要填这个，需要带上`/v1/chat/completions`
