### ISSUE TITLE
使用internlm_client，报错：KeyError: 'choices'

### ISSUE THREAD

**Issue by njzfw1024** [InternLM/MindSearch#118]
app.py:
![image](https://github.com/user-attachments/assets/5d4f47c6-eafe-4b0d-9916-8318aa500efa)

streamlit:
![image](https://github.com/user-attachments/assets/4f4ce77d-9765-47c0-bb88-5ce176238818)

**Comment by techflag** [comment]
链接qwen也是同样的错误

**Comment by liujiangning30** [comment]
> app.py: ![image](https://private-user-images.githubusercontent.com/130643833/356173390-5d4f47c6-eafe-4b0d-9916-8318aa500efa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODEyOTIsIm5iZiI6MTcyMzE4MDk5MiwicGF0aCI6Ii8xMzA2NDM4MzMvMzU2MTczMzkwLTVkNGY0N2M2LWVhZmUtNGIwZC05OTE2LTgzMThhYTUwMGVmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNTIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTQ1MTkzMjA5YzMxMDAxMGJkNzcyYTZkMTg0MTFkNTRlMWY4MGY5MmZjOWY5ZDIxN2JiMzQ4NDNjMTdhZGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v2h1Wp4qww6nbxtUNo-X46OuGSPbkKf-VGTHWU5nxjM)
> 
> streamlit: ![image](https://private-user-images.githubusercontent.com/130643833/356173556-4f4ce77d-9765-47c0-bb88-5ce176238818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODEyOTIsIm5iZiI6MTcyMzE4MDk5MiwicGF0aCI6Ii8xMzA2NDM4MzMvMzU2MTczNTU2LTRmNGNlNzdkLTk3NjUtNDdjMC1iYjg4LTVjZTE3NjIzODgxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNTIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzEzNTdmNGUyYzYxOTUxYjIwYjk0NmFhYzE1M2RhYjA1M2M4MWMyYzU3MjMwY2MzMDQ0YjIyMzBjYmVkNTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YenmL3qeGMrK_fTr6dpn79dC0ERwuTxqSfgxfR2ASeI)

Before using the model service, you need to start it with the command: `lmdeploy serve api_server internlm/internlm2_5-7b-chat --server-port 23333`.

**Comment by liujiangning30** [comment]
> 链接qwen也是同样的错误

qwen只能走GPTAPI

**Comment by chironliu** [comment]
> > 链接qwen也是同样的错误
> 
> qwen只能走GPTAPI

用qwen，需要那几步？

**Comment by chironliu** [comment]
> > 链接qwen也是同样的错误
> 
> qwen只能走GPTAPI

用qwen需要哪几步?

**Comment by usgDHJAKJD** [comment]
同求，调用qwen也出现类似问题

**Comment by liujiangning30** [comment]
> > > 链接qwen也是同样的错误
> > 
> > 
> > qwen只能走GPTAPI
> 
> 用qwen需要哪几步?

Option 1: 
```python
qwen_server = dict(type=LMDeployServer,
                       path='Qwen/Qwen2-7B-Instruct',
                       model_name='Qwen2-7B-Instruct',
                       ...)
```
Then, `python -m mindsearch.app --lang cn --model_format qwen_server`
                       
Option 2: 
First, Launching with lmdeploy CLI:
`lmdeploy serve api_server Qwen/Qwen2-7B-Instruct --server-port 23333`
Then, You can ping the backend model service as follows:
```python
qwen_client = dict(type=LMDeployClient,
                       model_name='Qwen2-7B-Instruct',
                       url='http://127.0.0.1:23333',
                       ...)
Finally, `python -m mindsearch.app --lang cn --model_format qwen_client`
```

Option 3: 
```python       
url = 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation'
qwen = dict(type=GPTAPI,
            model_type='qwen-max-longcontext',
            key=os.environ.get('QWEN_API_KEY', 'YOUR QWEN API KEY'),
            openai_api_base=url,
            ...)
```
Prerequisites: [Obtain an API key](https://help.aliyun.com/zh/dashscope/developer-reference/acquisition-and-configuration-of-api-key?spm=a2c4g.11186623.0.0.65fe46c1kNgoF9)
Then, `python -m mindsearch.app --lang cn --model_format qwen`

**Comment by meigami0** [comment]
> > > > 链接qwen也是同样的错误
> > > 
> > > 
> > > qwen只能走GPTAPI
> > 
> > 
> > 用qwen需要哪几步?
> 
> Option 1:
> 
> ```python
> qwen_server = dict(type=LMDeployServer,
>                        path='Qwen/Qwen2-7B-Instruct',
>                        model_name='Qwen2-7B-Instruct',
>                        ...)
> ```
> 
> Then, `python -m mindsearch.app --lang cn --model_format qwen_server`
> 
> Option 2: First, Launching with lmdeploy CLI: `lmdeploy serve api_server Qwen/Qwen2-7B-Instruct --server-port 23333` Then, You can ping the backend model service as follows:
> 
> ```python
> qwen_client = dict(type=LMDeployClient,
>                        model_name='Qwen2-7B-Instruct',
>                        url='http://127.0.0.1:23333',
>                        ...)
> Finally, `python -m mindsearch.app --lang cn --model_format qwen_client`
> ```
> 
> Option 3:
> 
> ```python
> url = 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation'
> qwen = dict(type=GPTAPI,
>             model_type='qwen-max-longcontext',
>             key=os.environ.get('QWEN_API_KEY', 'YOUR QWEN API KEY'),
>             openai_api_base=url,
>             ...)
> ```
> 
> Prerequisites: [Obtain an API key](https://help.aliyun.com/zh/dashscope/developer-reference/acquisition-and-configuration-of-api-key?spm=a2c4g.11186623.0.0.65fe46c1kNgoF9) Then, `python -m mindsearch.app --lang cn --model_format qwen`

本地使用Option 1和2两种方式加载internlm2_5-7b-chat模型都报问题图中问题
