### ISSUE TITLE
Support for azure openai, litellm

### ISSUE THREAD

**Issue by saitej123** [InternLM/MindSearch#120]
Please provide support for azure openai or litellm

**Comment by Harold-lkk** [comment]
Would you like to pull a request to support LiteLLM? Reference to https://github.com/InternLM/lagent/blob/a8ae3872fac6e23f832d860131a1196f1a722fe1/lagent/llms/openai.py#L21

**Comment by ssrheart425** [comment]
me too,I want to use litellm

**Comment by ssrheart425** [comment]
> Would you like to pull a request to support LiteLLM? Reference to https://github.com/InternLM/lagent/blob/a8ae3872fac6e23f832d860131a1196f1a722fe1/lagent/llms/openai.py#L21您想拉取支持 LiteLLM 的请求吗？参考 https://github.com/InternLM/lagent/blob/a8ae3872fac6e23f832d860131a1196f1a722fe1/lagent/llms/openai.py#L21

Using litellm, modifying openai_api_base does not work, and reports an error：

```
D:\pyEnvs\mindsearch\lib\site-packages\lagent\llms\openai.py:397: DeprecationWarning: `top_k` parameter is deprecated in OpenAI APIs.
warnings.warn(
{"detail":"Method Not Allowed"}
INFO:     127.0.0.1:3591 - "POST /solve HTTP/1.1" 200 OK
{"detail":"Method Not Allowed"}
```

**Comment by regstuff** [comment]
+1 for this. Is there a way to make it work with Azure? Thanks for the great app btw.
