### ISSUE TITLE
Getting error: INFO:mindsearch.agent.mindsearch_agent:Illegal reference id

### ISSUE THREAD

**Issue by snehpushp** [InternLM/MindSearch#122]
I'm using `groq` after some modifications in models.py file. Model is: `llama-3.1-8b-versatile`. Taken from #71 

Not always, but sometimes I'm getting the following error:

![image](https://github.com/user-attachments/assets/fc6c3cb1-41e8-45c9-aa1b-9e56d4de8960)

This generally happens when I try to ask a question which requires a lot of knowledge gathering. My query was:

`A detailed and elaborative article on "Life and Happiness". What do different peoples have opinion about it?`

**Comment by liujiangning30** [comment]
The core issue is that the model experienced hallucination, fabricating a reference page index.
https://github.com/InternLM/MindSearch/pull/127/files
