### ISSUE TITLE
本地运行的效果和官方的效果差距很大

### ISSUE THREAD

**Issue by pxz2016** [InternLM/MindSearch#125]
本地的测试效果要比官方的差很多
gpt-4o 和 bing
本地：北京今天的天气
![image](https://github.com/user-attachments/assets/e49f655d-b3f0-4b2f-b54e-9c917311986e)
官方：北京今天的天气
![image](https://github.com/user-attachments/assets/8e41fd4b-b711-4c70-bbe7-58794e6a8ded)

**Comment by wangr0031** [comment]
同感，和你一样的配置，感觉官方的服务好很多的

**Comment by pxz2016** [comment]
看结果是少了 对检索结果进行选择然后进一步获取内容

**Comment by pxz2016** [comment]
还有一个问题是会多次 请求 /solve，一直在反复

**Comment by Harold-lkk** [comment]
> 还有一个问题是会多次 请求 /solve，一直在反复

重复solve 是因为现在接口是 sse 长连接，如果切换了窗口会断联，这部分会加一个提示

**Comment by Harold-lkk** [comment]
> 看结果是少了 对检索结果进行选择然后进一步获取内容

搜索数目确实有变化，以及现在官方版本已经切换了20B模型

**Comment by wangr0031** [comment]
有些时候，会出现输出不完整的情况，例如下面的截图：
![image](https://github.com/user-attachments/assets/12368ac9-d438-448c-8b3d-5fd296d00aee)
后台日志里面也是一样的：
![image](https://github.com/user-attachments/assets/d13bfb07-57c2-4234-b3a8-db8f5d90986d)

**Comment by MyraBaba** [comment]
same here

**Comment by liujiangning30** [comment]
> 有些时候，会出现输出不完整的情况，例如下面的截图： ![image](https://private-user-images.githubusercontent.com/24863189/356539987-12368ac9-d438-448c-8b3d-5fd296d00aee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDkxMzAsIm5iZiI6MTcyMzQ0ODgzMCwicGF0aCI6Ii8yNDg2MzE4OS8zNTY1Mzk5ODctMTIzNjhhYzktZDQzOC00NDhjLThiM2QtNWZkMjk2ZDAwYWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA3NDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ODAwMWU1MDI1NzI4ZWEyYTQ5YTQ2NDIyMGI5NzBjMWVlZmQ4OGI3ZDFiMTc5NTlmOWI5YTQ3YjBjYmFhMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q0IzEeHdC0yO6jPn9CLpRUbpLTFoxGinwsjOfj2htX4) 后台日志里面也是一样的： ![image](https://private-user-images.githubusercontent.com/24863189/356540482-d13bfb07-57c2-4234-b3a8-db8f5d90986d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDkxMzAsIm5iZiI6MTcyMzQ0ODgzMCwicGF0aCI6Ii8yNDg2MzE4OS8zNTY1NDA0ODItZDEzYmZiMDctNTdjMi00MjM0LWIzYTgtZGI4ZjVkOTA5ODZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA3NDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YjJlNGZmYTA4YzU4ZTNlOTEwOTQ0MDU5NWU5Nzc4MTI2NzFhMGRiM2RkNzIwMDE0Yjg1NDViYTVjZTc2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P6eRTdfsB9ByBIXQCxNkRlH4ZLmyl3gyo6KfyCVNO1A)

https://github.com/InternLM/MindSearch/issues/111#issuecomment-2274842611

**Comment by wangr0031** [comment]
> > 有些时候，会出现输出不完整的情况，例如下面的截图： ![image](https://private-user-images.githubusercontent.com/24863189/356539987-12368ac9-d438-448c-8b3d-5fd296d00aee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDkxMzAsIm5iZiI6MTcyMzQ0ODgzMCwicGF0aCI6Ii8yNDg2MzE4OS8zNTY1Mzk5ODctMTIzNjhhYzktZDQzOC00NDhjLThiM2QtNWZkMjk2ZDAwYWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA3NDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ODAwMWU1MDI1NzI4ZWEyYTQ5YTQ2NDIyMGI5NzBjMWVlZmQ4OGI3ZDFiMTc5NTlmOWI5YTQ3YjBjYmFhMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q0IzEeHdC0yO6jPn9CLpRUbpLTFoxGinwsjOfj2htX4) 后台日志里面也是一样的： ![image](https://private-user-images.githubusercontent.com/24863189/356540482-d13bfb07-57c2-4234-b3a8-db8f5d90986d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDkxMzAsIm5iZiI6MTcyMzQ0ODgzMCwicGF0aCI6Ii8yNDg2MzE4OS8zNTY1NDA0ODItZDEzYmZiMDctNTdjMi00MjM0LWIzYTgtZGI4ZjVkOTA5ODZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA3NDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YjJlNGZmYTA4YzU4ZTNlOTEwOTQ0MDU5NWU5Nzc4MTI2NzFhMGRiM2RkNzIwMDE0Yjg1NDViYTVjZTc2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P6eRTdfsB9ByBIXQCxNkRlH4ZLmyl3gyo6KfyCVNO1A)
> 
> [#111 (comment)](https://github.com/InternLM/MindSearch/issues/111#issuecomment-2274842611)

thanks

**Comment by 1057520143** [comment]
请问GPT-4o 剧吐怎么配置的？我测接口一直报404，不知道是不是GPT配置问题
