### ISSUE TITLE
是否能只在查询实时性相关的内容采用搜索引擎，日常问答采用大模型

### ISSUE THREAD

**Issue by njzfw1024** [InternLM/MindSearch#128]
类似如下问题，大模型本身就可以回答，没必要再去从搜索引擎里找答案。
![image](https://github.com/user-attachments/assets/77e81aaa-3bf8-4839-8211-76a6e36da2a7)

**Comment by RobertLou** [comment]
而且我建议查询的时候增大实时性的占比，现在搜索前面的结果很多都没啥用，还有很多广告，污染了最终的输出结果。
