### ISSUE TITLE
assert CUDA_PATH is not None, 'Can not find $env:CUDA_PATH'

### ISSUE THREAD

**Issue by ericdfh** [InternLM/MindSearch#131]
when I want to debug locally and run 'python -m mindsearch.terminal', pop out err 'assert CUDA_PATH is not None, 'Can not find $env:CUDA_PATH''
![图片](https://github.com/user-attachments/assets/b1730bc8-024d-4843-90be-b6cc2a74ff0b)
how to fix it?

**Comment by rajyalakshmiadapala** [comment]
Hii same issue when Iam trying in windows os  . how to fix it?

**Comment by zol9527** [comment]
You need to install an executable file from invidia's website. Be careful about the version and pytorch. I can't give more information, cause I didn't start this project successfully haha.
