### ISSUE TITLE
输出结果是python的代码，不是搜索的结果

### ISSUE THREAD

**Issue by lizx0806** [InternLM/MindSearch#135]
在前端提问，输出的结果是python代码，而不是搜索结果，并且右边没有思考的过程。
LLM用的Qwen1.5B

![Snipaste_2024-08-10_18-36-48](https://github.com/user-attachments/assets/dfdaca74-45e8-4d59-a9ad-d848146a63d0)
![Snipaste_2024-08-10_18-36-34](https://github.com/user-attachments/assets/7a561118-f6b7-41e6-b667-17b02b869f08)
![Snipaste_2024-08-10_18-40-49](https://github.com/user-attachments/assets/439ba1e0-91ea-4ad6-867f-51ffb506d534)

**Comment by liujiangning30** [comment]
问题在于模型没有follow输出格式，`import websearchgraph as wsg`是捏造的，可以有针对性的微调[fewshot](https://github.com/InternLM/MindSearch/blob/00f0a82fae25256d899503cef4aee48e204f762e/mindsearch/agent/mindsearch_prompt.py#L277)

**Comment by datalee** [comment]
1.5B搞agent，玩呢，哈哈哈哈
