### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-3_1'. 

### ISSUE THREAD

**Issue by VersaceXcodes** [InternLM/MindSearch#142]
I am running gpt4 and keep getting this error in server, and keeps retrying the query although it gets some info and goes into loop of retrying with no success

```
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-3_1'.
/Users/moel/miniforge3/lib/python3.9/site-packages/lagent/actions/bing_browser.py:66: UserWarning: Retry 3/3 due to error: There is no current event loop in thread 'ThreadPoolExecutor-3_1'.
  warnings.warn(
/Users/moel/miniforge3/lib/python3.9/site-packages/lagent/actions/bing_browser.py:213: UserWarning: where to find reviews for top apps generated an exception: Failed to get search results from DuckDuckGo after retries.
  warnings.warn(f'{query} generated an exception: {exc}')
[{'type': 'text', 'content': '{}'}]`

**Comment by wangr0031** [comment]
maybe use bing search can resolve this issue

**Comment by liujiangning30** [comment]
Using a proxy might help, especially if there are network restrictions or regional blocks affecting your connection.
The [BingBrowser](https://github.com/InternLM/MindSearch/blob/d66aa86004390ac930593a69231966f95b0b3d3b/mindsearch/agent/__init__.py#L46) class takes an optional proxy parameter during initialization.
