### ISSUE TITLE
When i change the tab and return to it the process starts from the begging (this in React client)

### ISSUE THREAD

**Issue by MohamedAliRashad** [InternLM/MindSearch#145]
When i change the tab and return to it the process starts from the begging (this in React client)

**Comment by liujiangning30** [comment]
SSE (Server-Sent Events) has mechanisms to handle page visibility and reconnection after interruptions. If you switch away from the page during an active request and then return, SSE might re-establish the connection, causing the request to be repeated.

**Comment by MohamedAliRashad** [comment]
This shouldn't happen

**Comment by liujiangning30** [comment]
We'll resolve this issue in upcoming iterations
