### ISSUE TITLE
docker compose frontend is not connected to backend

### ISSUE THREAD

**Issue by MohamedAliRashad** [InternLM/MindSearch#152]
I submit a query on the frontend but the backend is not recieving anything

**Comment by Harold-lkk** [comment]
@lcolok

**Comment by lcolok** [comment]
> I submit a query on the frontend but the backend is not recieving anything

When you access the frontend, be aware of potential cross-origin issues. The current Docker Compose configuration serves as a starting point for the project, but it doesn't resolve all these issues that might be encountered in a production environment. 

You could check the documentation below to figure out how to fix this:

https://github.com/InternLM/MindSearch/blob/main/docker/README.md#cross-origin-access-considerations

**Comment by MohamedAliRashad** [comment]
I fixed the issue
```
export const GET_SSE_DATA = '/solve';
```
should have been
```
export const GET_SSE_DATA = 'http://0.0.0.0:8002/solve';
```
