### ISSUE TITLE
internlm2_5-7b-chat 不能正常产出运行代码构建图

### ISSUE THREAD

**Issue by CecGreg** [InternLM/MindSearch#161]
<img width="2142" alt="image" src="https://github.com/user-attachments/assets/f310ad31-8367-4745-bdca-d3c0d6113426">

**Comment by CecGreg** [comment]
只有文本推理步骤  没有产生构建图的python代码

**Comment by liujiangning30** [comment]
也许将temperature调到0.8会解决这个问题
