### ISSUE TITLE
本地部署显存不足如何多卡运行？

### ISSUE THREAD

**Issue by qing-tian-meng-ying** [InternLM/MindSearch#162]
llm = LMDeployServer(path='internlm/internlm2_5-7b-chat',
                     model_name='internlm2',
                     meta_template=INTERNLM2_META,
                     top_p=0.8,
                     top_k=1,
                     temperature=0,
                     max_new_tokens=8192,
                     repetition_penalty=1.02,
                     stop_words=['<|im_end|>'])
是从这里修改吗？

**Comment by mengrennwpu** [comment]
LMDeployServer中有个张量并行的tp参数可以设置，但貌似源码lmdeploy.api.py中的serve又将tp从kwargs中pop了，导致后面模型的初始化tp又成了1，不过手动改下就可以了。源码如下：
`from lmdeploy.serve.openai.api_client import APIClient
    from lmdeploy.serve.openai.api_server import serve

    if type(backend_config) is not PytorchEngineConfig:
        # set auto backend mode
        backend_config = autoget_backend_config(model_path, backend_config)
    backend = 'pytorch' if type(
        backend_config) is PytorchEngineConfig else 'turbomind'
    if 'tp' in kwargs:
        tp = kwargs['tp']
        kwargs.pop('tp')`

**Comment by mengrennwpu** [comment]
@qing-tian-meng-ying LMDeployServer中有个张量并行的tp参数可以设置，但貌似源码lmdeploy.api.py中的serve又将tp从kwargs中pop了，导致后面模型的初始化tp又成了1，不过手动改下就可以了。源码如下：

`python
def serve(model_path: str,
          model_name: Optional[str] = None,
          backend: Literal['turbomind', 'pytorch'] = 'turbomind',
          backend_config: Optional[Union[TurbomindEngineConfig,
                                         PytorchEngineConfig]] = None,
          chat_template_config: Optional[ChatTemplateConfig] = None,
          server_name: str = '0.0.0.0',
          server_port: int = 23333,
          log_level: str = 'ERROR',
          api_keys: Optional[Union[List[str], str]] = None,
          ssl: bool = False,
          **kwargs):
    """This will run the api_server in a subprocess.

    Args:
        model_path (str): the path of a model.
            It could be one of the following options:
                - i) A local directory path of a turbomind model which is
                    converted by `lmdeploy convert` command or download from
                    ii) and iii).
                - ii) The model_id of a lmdeploy-quantized model hosted
                    inside a model repo on huggingface.co, such as
                    "InternLM/internlm-chat-20b-4bit",
                    "lmdeploy/llama2-chat-70b-4bit", etc.
                - iii) The model_id of a model hosted inside a model repo
                    on huggingface.co, such as "internlm/internlm-chat-7b",
                    "Qwen/Qwen-7B-Chat ", "baichuan-inc/Baichuan2-7B-Chat"
                    and so on.
        model_name (str): needed when model_path is a pytorch model on
            huggingface.co, such as "internlm/internlm-chat-7b",
            "Qwen/Qwen-7B-Chat ", "baichuan-inc/Baichuan2-7B-Chat" and so on.
        backend (str): either `turbomind` or `pytorch` backend. Default to
            `turbomind` backend.
        backend_config (TurbomindEngineConfig | PytorchEngineConfig): backend
            config instance. Default to none.
        chat_template_config (ChatTemplateConfig): chat template configuration.
            Default to None.
        server_name (str): host ip for serving
        server_port (int): server port
        log_level(str): set log level whose value among [CRITICAL, ERROR, WARNING, INFO, DEBUG]
        api_keys (List[str] | str | None): Optional list of API keys. Accepts string type as
            a single api_key. Default to None, which means no api key applied.
        ssl (bool): Enable SSL. Requires OS Environment variables 'SSL_KEYFILE' and 'SSL_CERTFILE'.

    Return:
        APIClient: A client chatbot for LLaMA series models.

    Examples:
        >>> import lmdeploy
        >>> client = lmdeploy.serve('internlm/internlm-chat-7b', 'internlm-chat-7b')
        >>> for output in client.chat('hi', 1):
        ...    print(output)
    """ # noqa E501
    import time
    from multiprocessing import Process

    from lmdeploy.serve.openai.api_client import APIClient
    from lmdeploy.serve.openai.api_server import serve

    if type(backend_config) is not PytorchEngineConfig:
        # set auto backend mode
        backend_config = autoget_backend_config(model_path, backend_config)
    backend = 'pytorch' if type(
        backend_config) is PytorchEngineConfig else 'turbomind'
    if 'tp' in kwargs:
        tp = kwargs['tp']
        kwargs.pop('tp')
`

**Comment by Nuclear6** [comment]
应该就是这个参数的原因，执行lmdeploy serve api_server /work/internlm2_5-7b-chat --server-port 8089 --tp 1

RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/memory_utils.cu:32

执行 lmdeploy serve api_server /work/internlm2_5-7b-chat --server-port 8089 --tp 4

<img width="694" alt="image" src="https://github.com/user-attachments/assets/496d7b5f-ff3e-4f54-bcad-8104da678788">

我看我引入包tp设置也没问题，我再检查下

**Comment by Nuclear6** [comment]
修改这个文件中的python3.11/site-packages/lmdeploy/messages.py 141行tp: int = 4即可

tp 参数直接传递不生效
