### ISSUE TITLE
SearcherAgent基于internlm2_5-7b-chat在总结信息时给出的引用不正确

### ISSUE THREAD

**Issue by liam1985** [InternLM/MindSearch#167]
在构建graph并add_node的过程中，SearcherAgent会通过工具search并select所关注的网页内容，然后基于select到的网页内容总结得出相应结论，并给出支撑的引用。但是观察输入给模型的prompt，以及模型输出汇总的结论及支撑的引用，发现给出的引用所对应的content并不包含能支撑相应结论的事实。对于这种情况是否是因为模型internlm2_5-7b-chat在做总结引用的能力还有所欠缺，后续还需要对模型在这方面再进一步的调优。当前这种问题会导致最终输出的结论的可信度下降。

**Comment by liujiangning30** [comment]
Thanks for your advice. We will continue to optimize the ability of the InternLM series model on mindsearch.
