### ISSUE TITLE
Can not run with gpt4 model

### ISSUE THREAD

**Issue by RuiaRui** [InternLM/MindSearch#17]
I tried to run it locally with gpt4 (streamlit frontend), but I encountered the following error for any input. It seems there is an issue with streaming

File "/Users/.../mindsearch/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 211, in stream_chat
    for model_state, response, _ in self.llm.stream_chat(
File "/opt/homebrew/Caskroom/miniforge/base/envs/llm_env/lib/python3.11/site-packages/lagent/llms/openai.py", line 158, in stream_chat
    for text in self._stream_chat(messages, **gen_params):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/llm_env/lib/python3.11/site-packages/lagent/llms/openai.py", line 289, in streaming
    response = json.loads(decoded)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/llm_env/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/llm_env/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/llm_env/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by Harold-lkk** [comment]
Thank for your report, we will check it as soon as possible

**Comment by Harold-lkk** [comment]
https://github.com/InternLM/lagent/pull/217

**Comment by RuiaRui** [comment]
Hello, thank you very much for your attention to this issue. After the release of the new version of pr, there are still some errors when executing the search graph section (see below). I have tried different queries but always get the same error.




要回答这个问题，我们需要查询上海今天的天气情况，因为穿衣建议通常基于天气的温度、湿度等因素。

首先，我们将创建一个搜索图的根节点，代表这个问题。

<|action_start|><|interpreter|>```python
# 创建搜索图并添加根节点
web_search_graph = WebSearchGraph()
web_search_graph.add_root_node("上海今天适合穿什么衣服?")
```<|action_end|>
ERROR:mindsearch.agent.mindsearch_agent:Error executing code: 
Traceback (most recent call last):
  File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 349, in run_command
    assert plan_graph is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'searcher_resp_queue'")>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/llm_env/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../mindsearch/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 234, in stream_chat
    yield from self._process_code(
  File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 260, in _process_code
    for node_name, node, adj in self.execute_code(
  File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 368, in execute_code
    item = self.local_dict.get('graph').searcher_resp_queue.get(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'searcher_resp_queue'

**Comment by Harold-lkk** [comment]
```python
web_search_graph = WebSearchGraph()
web_search_graph.add_root_node("上海今天适合穿什么衣服?")
```
这个是因为他没有添加想要查询的节点，所以报错了

**Comment by LoganGrasby** [comment]
> Hello, thank you very much for your attention to this issue. After the release of the new version of pr, there are still some errors when executing the search graph section (see below). I have tried different queries but always get the same error.
> 
> 要回答这个问题，我们需要查询上海今天的天气情况，因为穿衣建议通常基于天气的温度、湿度等因素。
> 
> 首先，我们将创建一个搜索图的根节点，代表这个问题。
> 
> <|action_start|><|interpreter|>```python
> 
> # 创建搜索图并添加根节点
> web_search_graph = WebSearchGraph() web_search_graph.add_root_node("上海今天适合穿什么衣服?")
> 
> ```
> ERROR:mindsearch.agent.mindsearch_agent:Error executing code: 
> Traceback (most recent call last):
>   File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 349, in run_command
>     assert plan_graph is not None
>            ^^^^^^^^^^^^^^^^^^^^^^
> AssertionError
> ERROR:asyncio:Future exception was never retrieved
> future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'searcher_resp_queue'")>
> Traceback (most recent call last):
>   File "/opt/homebrew/Caskroom/miniforge/base/envs/llm_env/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/.../mindsearch/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
>     for response in agent.stream_chat(inputs):
>   File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 234, in stream_chat
>     yield from self._process_code(
>   File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 260, in _process_code
>     for node_name, node, adj in self.execute_code(
>   File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 368, in execute_code
>     item = self.local_dict.get('graph').searcher_resp_queue.get(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'searcher_resp_queue'
> ```

I ran into this issue as well and solved it by adding the following the the MindSearchAgent extract code function:

` text = re.sub('(web_)?search_graph', 'graph', text)`

**Comment by RuiaRui** [comment]
> > Hello, thank you very much for your attention to this issue. After the release of the new version of pr, there are still some errors when executing the search graph section (see below). I have tried different queries but always get the same error.
> > 要回答这个问题，我们需要查询上海今天的天气情况，因为穿衣建议通常基于天气的温度、湿度等因素。
> > 首先，我们将创建一个搜索图的根节点，代表这个问题。
> > <|action_start|><|interpreter|>```python
> > # 创建搜索图并添加根节点
> > web_search_graph = WebSearchGraph() web_search_graph.add_root_node("上海今天适合穿什么衣服?")
> > ```
> > ERROR:mindsearch.agent.mindsearch_agent:Error executing code: 
> > Traceback (most recent call last):
> >   File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 349, in run_command
> >     assert plan_graph is not None
> >            ^^^^^^^^^^^^^^^^^^^^^^
> > AssertionError
> > ERROR:asyncio:Future exception was never retrieved
> > future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'searcher_resp_queue'")>
> > Traceback (most recent call last):
> >   File "/opt/homebrew/Caskroom/miniforge/base/envs/llm_env/lib/python3.11/concurrent/futures/thread.py", line 58, in run
> >     result = self.fn(*self.args, **self.kwargs)
> >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/Users/.../mindsearch/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
> >     for response in agent.stream_chat(inputs):
> >   File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 234, in stream_chat
> >     yield from self._process_code(
> >   File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 260, in _process_code
> >     for node_name, node, adj in self.execute_code(
> >   File "/Users/.../mindsearch/MindSearch/mindsearch/agent/mindsearch_agent.py", line 368, in execute_code
> >     item = self.local_dict.get('graph').searcher_resp_queue.get(
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > AttributeError: 'NoneType' object has no attribute 'searcher_resp_queue'
> > ```
> 
> I ran into this issue as well and solved it by adding the following the the MindSearchAgent extract_code function:
> 
> ` text = re.sub('(web_)?search_graph', 'graph', text)`

Thank you so much. This fixed my issue. Now it can work with gpt4 and Gpt-4o-mini(with some chances to fail)

**Comment by Harold-lkk** [comment]
https://github.com/InternLM/MindSearch/pull/29

**Comment by bakongi** [comment]
Here is solution:

https://github.com/InternLM/MindSearch/issues/53

**Comment by MyraBaba** [comment]
@RuiaRui 

Hi Have you solved the problem :  json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Can you provided full modified files if you solved ?

**Comment by bakongi** [comment]
> @RuiaRui
> 
> Hi Have you solved the problem : json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
> 
> Can you provided full modified files if you solved ?

https://github.com/InternLM/MindSearch/issues/53

**Comment by RuiaRui** [comment]
> @RuiaRui
> 
> Hi Have you solved the problem : json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
> 
> Can you provided full modified files if you solved ?

Hi, I solved it by updating the lagent lib [here](https://github.com/InternLM/lagent/pull/217)
