### ISSUE TITLE
planner中模型internlm2_5-7b-chat生成的代码问题

### ISSUE THREAD

**Issue by liam1985** [InternLM/MindSearch#172]
![image](https://github.com/user-attachments/assets/a0d188d2-7092-412d-ab58-212b592b82fc)
提出问题：上海今天校园男生适合穿什么衣服
模型planning的时候直接生成串联的三个节点，这个应该存在问题。按照道理说，planner应该先生成一个节点，当该节点处理汇总完后返回planner，planner根据结果再生成代码生成下一个节点。

**Comment by liujiangning30** [comment]
We will continue to optimize the ability of the InternLM series model on mindsearch.
