### ISSUE TITLE
the models not has auto download features 

### ISSUE THREAD

**Issue by al-swaiti** [InternLM/MindSearch#18]
i run the server used all options , but the models was not start downloading , then i downloaded them using transformer also not loaded any help or walk through

**Comment by Harold-lkk** [comment]
Thank for your report, we will check it as soon as possible

**Comment by Harold-lkk** [comment]
We will not load the model until you call the API in frontend. Do you call the api in frontend or fastapi page?

**Comment by Harold-lkk** [comment]
Close this issue for not replying. Feel free to reopen it.
