### ISSUE TITLE
docker-compose部署完之后  默认的模型一直没有开始下载

### ISSUE THREAD

**Issue by cds-1993** [InternLM/MindSearch#184]
使用docker-compose部署完之后   前端可以正常访问  提问了一下之后容器日志中没有看到下载模型相关的日志   映射的路径也一直是空的，请问怎么排查？

![image](https://github.com/user-attachments/assets/cb1c1c9b-a2b5-4f72-9bdf-1fb0c85fce57)

![image](https://github.com/user-attachments/assets/e3a2465e-cc1a-4ef7-be31-b28057890182)

**Comment by lcolok** [comment]
@cds-1993 能否提供一下浏览器的调控台信息和网络请求信息，以及是后端的运行日志，这样可以有助于判断是哪个环节出现问题。

**Comment by cds-1993** [comment]
![image](https://github.com/user-attachments/assets/5342fa72-5589-47e9-99a2-2ecb3fcd3b82)
![image](https://github.com/user-attachments/assets/3eb118f0-467d-4d29-b9f3-4e28866e0b03)
![image](https://github.com/user-attachments/assets/bf36db4d-339a-4d1a-9cf6-566502ae35f0)
收集信息如上

**Comment by cds-1993** [comment]
![image](https://github.com/user-attachments/assets/5342fa72-5589-47e9-99a2-2ecb3fcd3b82)
![image](https://github.com/user-attachments/assets/3eb118f0-467d-4d29-b9f3-4e28866e0b03)
![image](https://github.com/user-attachments/assets/bf36db4d-339a-4d1a-9cf6-566502ae35f0)
收集信息如上

**Comment by lcolok** [comment]
@cds-1993 请拉取最新版本，再重新部署试试
