### ISSUE TITLE
有些结果很离谱

### ISSUE THREAD

**Issue by datalee** [InternLM/MindSearch#19]
![image](https://github.com/user-attachments/assets/5fed81f5-f5bd-4320-9acf-6fc6ec509058)

**Comment by Harold-lkk** [comment]
现在网页解析这部分是直接 request 获取的 一些金牌表格的数据 3   4   xx 金银牌的数据 就被拼接在一块，导致回复的时候就被低质量网页内容污染了

**Comment by datalee** [comment]
> 现在网页解析这部分是直接 request 获取的 一些金牌表格的数据 3 4 xx 金银牌的数据 就被拼接在一块，导致回复的时候就被低质量网页内容污染了

ok，懂了。另外我想问下，9；17 这种蓝色的引用能直接关联到或者跳转到对应的段落吗？

**Comment by Harold-lkk** [comment]
现在后端是有返回对应的链接的，不过前端界面暂时还在设计，还没支持
