### ISSUE TITLE
那个docker 部署 文档能写全点吗  安装不下去

### ISSUE THREAD

**Issue by zhuhuashan** [InternLM/MindSearch#191]

**Comment by lcolok** [comment]
@zhuhuashan 您可以看看最新的部署方法：https://github.com/InternLM/MindSearch/blob/main/docker/README_zh-CN.md 几乎是一键部署的，请你尝试一下。

**Comment by dididada002** [comment]
@lcolok 请问这个报错是因为我本地环境的问题吗：
![企业微信截图_967d333e-dd10-49a8-a31e-8324fecfe405](https://github.com/user-attachments/assets/76983dc6-6b17-4f49-9660-28a74353d4c7)

**Comment by lcolok** [comment]
> @lcolok 请问这个报错是因为我本地环境的问题吗： ![企业微信截图_967d333e-dd10-49a8-a31e-8324fecfe405](https://private-user-images.githubusercontent.com/43565339/364213950-76983dc6-6b17-4f49-9660-28a74353d4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjEyMjgsIm5iZiI6MTcyNTQyMDkyOCwicGF0aCI6Ii80MzU2NTMzOS8zNjQyMTM5NTAtNzY5ODNkYzYtNmIxNy00ZjQ5LTk2NjAtMjhhNzQzNTNkNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAzMzUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMWE3OTA4ZWMyNjcwYjQxZTVjMmZmNTY3ZjExOGY5ZTA2MTg4MTQwYTdlZTBkY2FhNDBiYWNmNjY4MmFjMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.es35y8jRl6FMxoL7VOjfsdAM3FdxVD0YEX1U_65tyyQ)

可能是权限问题，请你尝试一下加上 `sudo` 来执行，意思就是 
```
sudo msdl
```

**Comment by dididada002** [comment]
> > @lcolok 请问这个报错是因为我本地环境的问题吗： ![企业微信截图_967d333e-dd10-49a8-a31e-8324fecfe405](https://private-user-images.githubusercontent.com/43565339/364213950-76983dc6-6b17-4f49-9660-28a74353d4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjEyMjgsIm5iZiI6MTcyNTQyMDkyOCwicGF0aCI6Ii80MzU2NTMzOS8zNjQyMTM5NTAtNzY5ODNkYzYtNmIxNy00ZjQ5LTk2NjAtMjhhNzQzNTNkNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAzMzUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMWE3OTA4ZWMyNjcwYjQxZTVjMmZmNTY3ZjExOGY5ZTA2MTg4MTQwYTdlZTBkY2FhNDBiYWNmNjY4MmFjMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.es35y8jRl6FMxoL7VOjfsdAM3FdxVD0YEX1U_65tyyQ)
> 
> 可能是权限问题，请你尝试一下加上 `sudo` 来执行，意思就是
> 
> ```
> sudo msdl
> ```

您好感谢您的解答，已解决，需要手动创建temp文件夹

**Comment by lcolok** [comment]
> > > @lcolok 请问这个报错是因为我本地环境的问题吗： ![企业微信截图_967d333e-dd10-49a8-a31e-8324fecfe405](https://private-user-images.githubusercontent.com/43565339/364213950-76983dc6-6b17-4f49-9660-28a74353d4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjEyMjgsIm5iZiI6MTcyNTQyMDkyOCwicGF0aCI6Ii80MzU2NTMzOS8zNjQyMTM5NTAtNzY5ODNkYzYtNmIxNy00ZjQ5LTk2NjAtMjhhNzQzNTNkNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAzMzUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMWE3OTA4ZWMyNjcwYjQxZTVjMmZmNTY3ZjExOGY5ZTA2MTg4MTQwYTdlZTBkY2FhNDBiYWNmNjY4MmFjMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.es35y8jRl6FMxoL7VOjfsdAM3FdxVD0YEX1U_65tyyQ)
> > 
> > 
> > 可能是权限问题，请你尝试一下加上 `sudo` 来执行，意思就是
> > ```
> > sudo msdl
> > ```
> 
> 您好感谢您的解答，已解决，需要手动创建temp文件夹

感谢反馈问题，temp文件夹这块要补全一下逻辑，现在没有自动创建

**Comment by Alerson-Z** [comment]
File "/Users/evan/opt/miniconda3/bin/msdl", line 33, in <module>
    sys.exit(load_entry_point('msdl', 'console_scripts', 'msdl')())
  File "/Volumes/secDisk/Downloads/MindSearch-main/docker/msdl/__main__.py", line 192, in main
    print(t("UNEXPECTED_ERROR", error=str(e)))
  File "/Volumes/secDisk/Downloads/MindSearch-main/docker/msdl/i18n.py", line 38, in t
    return i18n.t(key, **kwargs)
  File "/Users/evan/opt/miniconda3/lib/python3.9/site-packages/i18n/translator.py", line 26, in t
    resource_loader.search_translation(key, locale)
  File "/Users/evan/opt/miniconda3/lib/python3.9/site-packages/i18n/resource_loader.py", line 103, in search_translation
    load_directory(directory, locale)
  File "/Users/evan/opt/miniconda3/lib/python3.9/site-packages/i18n/resource_loader.py", line 93, in load_directory
    load_translation_file(f, directory, locale)
  File "/Users/evan/opt/miniconda3/lib/python3.9/site-packages/i18n/resource_loader.py", line 72, in load_translation_file
    translations_dic = load_resource(os.path.join(base_directory, filename), root_data)
  File "/Users/evan/opt/miniconda3/lib/python3.9/site-packages/i18n/resource_loader.py", line 24, in load_resource
    return getattr(loaders[extension], "load_resource")(filename, root_data)
  File "/Users/evan/opt/miniconda3/lib/python3.9/site-packages/i18n/loaders/loader.py", line 48, in load_resource
    raise I18nFileLoadError("error getting data from {0}: {1} not defined".format(filename, root_data))
这个大概是原因

**Comment by lcolok** [comment]
@Alerson-Z 初步推断是权限问题或者是文件系统的路径问题，建议先试试加上 sudo 来执行，我稍后会使用Mac去排查问题
