### ISSUE TITLE
docker启动系统后，想要修改前端的端口应该在哪里修改呢？

### ISSUE THREAD

**Issue by Ansrg123** [InternLM/MindSearch#194]
docker启动系统后，想要修改前端的端口应该在哪里修改呢？

**Comment by lcolok** [comment]
要修改前端的端口映射，您需要按以下步骤操作：

1. 找到配置文件：定位到 `MindSearch/docker/msdl/templates/docker-compose.yaml` 文件。

2. 在文件中定位 `frontend` 服务的配置部分。

3. 找到 `ports` 配置项。它的格式通常是 `"主机端口:容器端口"`。例如：

   ```yaml
   ports:
     - "8080:8080"
   ```

4. 修改主机端口（左侧数值）：这是您想要在主机上使用的新端口号。容器端口（右侧数值）保持不变，因为这是应用在容器内部使用的端口。

5. 例如，如果您想将前端服务映射到主机的 18080 端口，可以这样修改：

   ```yaml
   ports:
     - "18080:8080"
   ```

6. 保存文件并重新启动 Docker 容器以应用更改。

请注意，修改端口后，您需要使用新的端口号来访问前端服务。例如，如果之前通过 `http://localhost:8080` 访问，现在需要使用 `http://localhost:18080`。
