### ISSUE TITLE
请问是用的bing搜索吗

### ISSUE THREAD

**Issue by Zhaobudaoyuema** [InternLM/MindSearch#20]
这要是我直接部署，是不是需要自己设置key。有没有一些免费的搜索可以用于替换呢。还有我感觉是不是会很依赖搜索，要是搜不到或者搜索返回结果不行，那就也没法进行
![image](https://github.com/user-attachments/assets/92b5bb36-262d-4c57-9ff8-7aaecee378d8)

**Comment by Harold-lkk** [comment]
现在用的是 DuckDuckGo 的搜索，他提供了免费的搜索，就是并发比较差，有rate limit
