### ISSUE TITLE
[Update]GPTAPI系列模型能稳定调用MindSearch的参数配置

### ISSUE THREAD

**Issue by MING-ZCH** [InternLM/MindSearch#216]
如题，计划采用GPT系列模型（GPT-4/4o），请问有无推荐的可稳定运行检索的temperature, top_p, top_k等参数建议？
已进行如下尝试：
* GPT-4o-mini: temperature: 0, top_p: 0.8, top_k=1，无法成功调用搜索
* GPT-4o: temperature: 0, top_p: 0.8, top_k=1，无法成功调用搜索
![image](https://github.com/user-attachments/assets/e54de5d5-b60f-4367-82d4-60259fdc28c5)

**Comment by Tejaswgupta** [comment]
@MING-ZCH what was the resolution?
