### ISSUE TITLE
你好，能改或者指定搜索引擎吗？

### ISSUE THREAD

**Issue by datalee** [InternLM/MindSearch#22]
看着默认是bing？BingBrowser.search

**Comment by Harold-lkk** [comment]
现在实际用的是 DuckDuckGo 的服务， 如果想替换不同搜索引擎，可以自己实现一个[搜索后端](https://github.com/InternLM/lagent/blob/47f866176b7a238f44c80ecbc0649050c52f6914/lagent/actions/bing_browser.py#L174) 即可

**Comment by datalee** [comment]
> 现在实际用的是 DuckDuckGo 的服务， 如果想替换不同搜索引擎，可以自己实现一个[搜索后端](https://github.com/InternLM/lagent/blob/47f866176b7a238f44c80ecbc0649050c52f6914/lagent/actions/bing_browser.py#L174) 即可

网络调用不同，这个需要配置什么key吗？

**Comment by Harold-lkk** [comment]
这个应该是你的网络问题，可以配置一下代理

**Comment by datalee** [comment]
> 这个应该是你的网络问题，可以配置一下代理

ok，done！

**Comment by Yue-Rain** [comment]
请教一下这个代理怎么配置？谢谢！

**Comment by datalee** [comment]
> 请教一下这个代理怎么配置？谢谢！

我是直接在duckduckgo加了proxy

**Comment by datalee** [comment]
> 现在实际用的是 DuckDuckGo 的服务， 如果想替换不同搜索引擎，可以自己实现一个[搜索后端](https://github.com/InternLM/lagent/blob/47f866176b7a238f44c80ecbc0649050c52f6914/lagent/actions/bing_browser.py#L174) 即可

这个是可以的，不过需要改那个lagent的源码，新增一个类，然后在init_agent的时候，传入你新定义的searcher_type

**Comment by usgDHJAKJD** [comment]
> > 现在实际用的是 DuckDuckGo 的服务， 如果想替换不同搜索引擎，可以自己实现一个[搜索后端](https://github.com/InternLM/lagent/blob/47f866176b7a238f44c80ecbc0649050c52f6914/lagent/actions/bing_browser.py#L174) 即可
> 
> 这个是可以的，不过需要改那个lagent的源码，新增一个类，然后在init_agent的时候，传入你新定义的searcher_type



> > 请教一下这个代理怎么配置？谢谢！
> 
> 我是直接在duckduckgo加了proxy

请问proxy代理是在哪个网站上申请的
