### ISSUE TITLE
docker安装中，运行msdl后报错

### ISSUE THREAD

**Issue by Belonger** [InternLM/MindSearch#222]
pip install -e .   正常运行
![QQ截图20241021093438](https://github.com/user-attachments/assets/8238feda-745a-4139-9f49-8eea203bdaaf)

msdl报错
![QQ截图20241021093452](https://github.com/user-attachments/assets/aeb5b456-d1d0-45b5-8b8d-84e783d14311)

**Comment by xmx666** [comment]
同样的错误

**Comment by Harold-lkk** [comment]
@lcolok
