### ISSUE TITLE
前端存储的nodesinfo全是空值

### ISSUE THREAD

**Issue by JansonChenQ** [InternLM/MindSearch#228]
![image](https://github.com/user-attachments/assets/ac637cdf-ee01-4063-8ac9-c788477a8508)
分析完成后，再点击思维的详情，发现前端NodesInfo中存储的数据都是空值。
![image](https://github.com/user-attachments/assets/43b718fb-4df5-497b-be39-62ef38cdcc47)

**Comment by Harold-lkk** [comment]
可以试用一下新版本
