### ISSUE TITLE
有微信群吗？React 页面问问题，没有反应, gradio是可以的

### ISSUE THREAD

**Issue by chuanzhubin** [InternLM/MindSearch#232]
1. 求个微信群
2. React 页面问问题，没有反应, gradio和streamlit是可以的。
```
Request URL:
http://127.0.0.1:8080/solve
Request Method:
POST
Status Code:
404 Not Found
```

**Comment by chuanzhubin** [comment]
互助群

![678f31aa5055ac699b1acf8f26db30f](https://github.com/user-attachments/assets/0aea6161-925d-4d13-8842-0f6a02c67ef7)

**Comment by Harold-lkk** [comment]
可以用新版本试一下

**Comment by brewswang** [comment]
群的二维码能再发一下吗？

**Comment by lzz999997** [comment]
可以再求一个互助群吗？
