### ISSUE TITLE
请问腾讯搜素引擎的TENCENT_SEARCH_SECRET_ID和TENCENT_SEARCH_SECRET_KEY在哪里获取

### ISSUE THREAD

**Issue by xiangcaoximilu** [InternLM/MindSearch#246]
请问腾讯搜素引擎的TENCENT_SEARCH_SECRET_ID和TENCENT_SEARCH_SECRET_KEY在哪里获取

**Comment by HaishengLiang** [comment]
公开的API只有[TextModeration](https://cloud.tencent.com/document/api/1124/51860)
SearchCommon的action要什么情况才能开通？
