### ISSUE TITLE
请问有没有降低延迟的方法啊？

### ISSUE THREAD

**Issue by babytdream** [InternLM/MindSearch#250]
每次输出很多中间过程很耗时，延迟很高，有什么好的办法吗？
体验了perplexity ai，感觉他们的延迟就很低。
谢谢！

**Comment by Harold-lkk** [comment]
延迟时间是和问题复杂度(对应到mindsearch 节点数)以及阅读的网页数目线性相关的， 如果想提速可以减少浏览器搜索结果返回的数目
