### ISSUE TITLE
官方的demo基本可以稳定运行，为啥github上代码跑起来这么不稳定？

### ISSUE THREAD

**Issue by chuanzhubin** [InternLM/MindSearch#251]
官方的demo基本可以稳定运行，为啥github上代码跑起来这么不稳定？
bug特别多，难道官方还有另一个库在维护？

**Comment by xiongvalerio** [comment]
> 官方的demo基本可以稳定运行，为啥github上代码跑起来这么不稳定？
> bug特别多，难道官方还有另一个库在维护？

我也这么感觉

**Comment by Harold-lkk** [comment]
实际就是一套代码呀😕

**Comment by HaishengLiang** [comment]
感觉官方的搜索比我本地的快好多啊，感觉都不像duckduckgo的底座了，是不是用了bing或者其他产品了

**Comment by Harold-lkk** [comment]
我们 demo 用了付费的API

**Comment by HaishengLiang** [comment]
新版的代码应该没开源 我对比了下编译产物的代码 
跟目前github上的内容不完全匹配 giithub的代码至少落后了1-2个版本

**Comment by Harold-lkk** [comment]
前端因为是官方平台 代码有一些适配可能有略微差异在，所有的后端代码均一致 启动后端的服务就我们提供的dockerfile
