### ISSUE TITLE
Demo application doesn't run

### ISSUE THREAD

**Issue by Tejaswgupta** [InternLM/MindSearch#254]
I setup the demo using gpt-4o-mini and BraveSearch but it never goes ahead of the first step. 

<img width="2236" alt="Screenshot 2024-11-14 at 8 31 17 PM" src="https://github.com/user-attachments/assets/d2d345b7-1e13-4d6b-bbec-7912d3abe3db">

The server terminal just keeps printing blank spaces.
<img width="1386" alt="Screenshot 2024-11-14 at 8 32 37 PM" src="https://github.com/user-attachments/assets/7b96a11b-ef9d-4c48-a148-8b17d0d28006">

Am i missing something?

**Comment by braisedpork1964** [comment]
The default system prompts with tool invocation protocol are not easy for models other than InternLM2.5-Chat to follow. I think someone got the same problem after switching to GPT4.

A possible solution is to concatenate the system prompt and fewshot prompt, and loosen the `begin` and `end` pattern of tool parsers. See https://github.com/InternLM/MindSearch/issues/249#issuecomment-2472680114
