### ISSUE TITLE
书生2.5-7b模型在引用上的幻觉问题

### ISSUE THREAD

**Issue by datalee** [InternLM/MindSearch#26]
下面是searcher的结果：
`RAG（Retrieval-Augmented Generation）作为一种基于检索增强生成的技术，其未来发展方向主要集中在以下几个方面：

1. **多模态支持**：
   RAG不仅限于文本生成，还可以应用于多模态领域，如图像、音频等。通过结合不同类型的数据，RAG可以生成更加丰富和多样化的内容。例如，微软研究院的新方法GraphRAG便是在查询时执行提示词的增强，利用私有数据集创建知识图谱，并将图谱与机器学习一同用于增强生成过程[[1]]。

2. **领域专长**：
   RAG能够利用特定领域或组织的内部知识库，而无需重新训练模型。这使得它在处理垂直、专业领域的任务时表现出色。例如，RAG可以结合特定领域的知识库，生成更加精准和专业的内容[[9]]。

3. **高效性**：
   RAG通过访问外部知识库，避免了重新训练模型的成本和时间消耗，是一种经济高效的改进方法。未来，RAG可能会进一步优化检索和增强过程，提高生成效率和质量[[9]]。

4. **长上下文生成**：
   未来的RAG系统将利用长上下文生成的能力，以提升最终性能。通过结合检索和生成技术，RAG可以生成更加连贯和逻辑性强的文本，从而提高生成文本的质量[[2]]。

5. **知识冲突和解决**：
   RAG在处理多源信息时可能会遇到知识冲突的问题。未来，RAG可能会发展出更高级的冲突解决机制，以确保生成内容的准确性和一致性。例如，清华大学、西湖大学和香港中文大学联合发布的论文探讨了RAG大模型知识冲突的问题，并提出了相应的解决方案[[15]]。

6. **技术优化和提升**：
   未来的研究方向将关注开发更先进的方法来提升和应用RAG。例如，检索器和生成器之间的结合方法、优化提升技术等都是未来研究的重要方向[[2]]。

综上所述，RAG未来的发展方向包括多模态支持、领域专长、高效性、长上下文生成、知识冲突解决以及技术优化和提升。这些方向将推动RAG在生成内容的质量、效率和多样性方面取得更大的进步。`

**Comment by datalee** [comment]
然后，下面是最后planner的结果：
`RAG（Retrieval-Augmented Generation）作为一种基于检索增强生成的技术，其未来发展方向主要集中在以下几个方面：

1. **多模态支持**：
   RAG不仅限于文本生成，还可以应用于多模态领域，如图像、音频等。通过结合不同类型的数据，RAG可以生成更加丰富和多样化的内容。例如，微软研究院的新方法GraphRAG便是在查询时执行提示词的增强，利用私有数据集创建知识图谱，并将图谱与机器学习一同用于增强生成过程[[11]]。

2. **领域专长**：
   RAG能够利用特定领域或组织的内部知识库，而无需重新训练模型。这使得它在处理垂直、专业领域的任务时表现出色。例如，RAG可以结合特定领域的知识库，生成更加精准和专业的内容[[19]]。

3. **高效性**：
   RAG通过访问外部知识库，避免了重新训练模型的成本和时间消耗，是一种经济高效的改进方法。未来，RAG可能会进一步优化检索和增强过程，提高生成效率和质量[[19]]。

4. **长上下文生成**：
   未来的RAG系统将利用长上下文生成的能力，以提升最终性能。通过结合检索和生成技术，RAG可以生成更加连贯和逻辑性强的文本，从而提高生成文本的质量[[12]]。

5. **知识冲突和解决**：
   RAG在处理多源信息时可能会遇到知识冲突的问题。未来，RAG可能会发展出更高级的冲突解决机制，以确保生成内容的准确性和一致性。例如，清华大学、西湖大学和香港中文大学联合发布的论文探讨了RAG大模型知识冲突的问题，并提出了相应的解决方案[[25]]。

6. **技术优化和提升**：
   未来的研究方向将关注开发更先进的方法来提升和应用RAG。例如，检索器和生成器之间的结合方法、优化提升技术等都是未来研究的重要方向[[12]]。

综上所述，RAG未来的发展方向包括多模态支持、领域专长、高效性、长上下文生成、知识冲突解决以及技术优化和提升。这些方向将推动RAG在生成内容的质量、效率和多样性方面取得更大的进步。`

### **引用2变成了12,15变成了25等**

**Comment by ZwwWayne** [comment]
小模型的幻觉确实比较明显。这是后续改进的重要方向之一。
目前有需要的话，可以尝试使用 gpt4o 或者 claude

**Comment by Harold-lkk** [comment]
这个引用 Index Search 和 Planner 确实不是一样的，因为Planner 要见到很多 Searcher 的返回结果，每个Seacher的索引都是从 0 开始的，所以我们把Searcher 的结果给到 Planner时修改了索引 ID

**Comment by datalee** [comment]
> 这个引用 Index Search 和 Planner 确实不是一样的，因为Planner 要见到很多 Searcher 的返回结果，每个Seacher的索引都是从 0 开始的，所以我们把Searcher 的结果给到 Planner时修改了索引 ID

那如何对应起来？
