### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by hsjlyj** [InternLM/MindSearch#28]
怎么解决了
这个不需要配置搜索引擎吗 
例如search serper等

**Comment by Harold-lkk** [comment]
搜索引擎默认配置了一个免费的引擎，不用配置

**Comment by hsjlyj** [comment]
已经删了 后续能支持更多api的接入吗 目前也没详细的配置方法 one-api这种接入方式还是很普遍的 能不能像openweb-ui那样填入base_url和api key自动识别模型 可以自由选择搜索引擎

**Comment by Harold-lkk** [comment]
将来会接入更多的API的，现在实际各家模型在单纯的对话api比较对齐 但是在一些调用工具这些不太一致，我们也能适配各家api
