### ISSUE TITLE
必须要使用lmdeploy==0.2.3版本吗

### ISSUE THREAD

**Issue by shell-nlp** [InternLM/MindSearch#31]
我使用lmdeploy==0.5.2 ，但是模型生成代码的时候 没有生成 特殊token  <|action_start|><|interpreter|>

**Comment by Harold-lkk** [comment]
有返回的内容么可以截个图

**Comment by shell-nlp** [comment]
> 有返回的内容么可以截个图
![image](https://github.com/user-attachments/assets/f7e1b69f-85bc-4900-9cce-6118faa58448)

这是我打印的模型输出，并没有 <|action_start|><|interpreter|>

**Comment by shell-nlp** [comment]
导致 代码无法解析成功

**Comment by Harold-lkk** [comment]
重复几次可以稳定复现么？ 我们现在用的确实是0.2.3 现在我们自己测试下来也会存在不同版本的lmdeploy因为做了一些重构导致新版本和老版本返回结果差异比较大

**Comment by Harold-lkk** [comment]
有问题可以随时在追问
