### ISSUE TITLE
no results are shown

### ISSUE THREAD

**Issue by tfriedel** [InternLM/MindSearch#33]
I tried a few english queries on the playground, it's busy for some time but then a blank page.

**Comment by CharryLee0426** [comment]
Check your back end logging info. It maybe an error occured. I can't run it successfully.

**Comment by Harold-lkk** [comment]
We apologize for the poor experience. Our current concurrency is very low, and we are not in a commercial deployment. The usage is indeed quite high at the moment, which is causing the slowness.

**Comment by Harold-lkk** [comment]
It's easy to build locally. If you encounter any issues, feel free to ask at any time.

**Comment by Harold-lkk** [comment]
Maybe try again.
