### ISSUE TITLE
ERROR: No matching distribution found for lmdeploy==0.2.3

### ISSUE THREAD

**Issue by sdhou** [InternLM/MindSearch#34]
pip install -r requirements.txt
Looking in indexes: https://mirror.sjtu.edu.cn/pypi/web/simple
Collecting git+https://github.com/InternLM/lagent.git (from -r requirements.txt (line 4))
  Cloning https://github.com/InternLM/lagent.git to /tmp/pip-req-build-wo9i281c
  Running command git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git /tmp/pip-req-build-wo9i281c
  Resolved https://github.com/InternLM/lagent.git to commit 47f866176b7a238f44c80ecbc0649050c52f6914
  Preparing metadata (setup.py) ... done
Requirement already satisfied: duckduckgo_search==5.3.1b1 in /home/westwell/miniconda3/envs/mindsearch/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (5.3.1b1)
Requirement already satisfied: einops in /home/westwell/miniconda3/envs/mindsearch/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: fastapi in /home/westwell/miniconda3/envs/mindsearch/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (0.111.1)
Requirement already satisfied: gradio in /home/westwell/miniconda3/envs/mindsearch/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (4.39.0)
Requirement already satisfied: janus in /home/westwell/miniconda3/envs/mindsearch/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (1.0.0)
ERROR: Could not find a version that satisfies the requirement lmdeploy==0.2.3 (from versions: 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.2.post1)
ERROR: No matching distribution found for lmdeploy==0.2.3
python -V
Python 3.12.4

**Comment by Harold-lkk** [comment]
https://github.com/InternLM/MindSearch/blob/883c66c7340a9196e29a1e166a39f86bb8a17af2/requirements.txt#L7
You can remove the version limit. But different lmdeploy versions may have different performance
