### ISSUE TITLE
运行后，请求发送无响应

### ISSUE THREAD

**Issue by yangjq713** [InternLM/MindSearch#35]
1. 在单张4090上运行internlm/internlm2_5-7b-chat
2. 运行terninal程序，在加载模型，完成lmdeploy的日志打印后，程序无其他信息输出
3.
![微信截图_20240801110135](https://github.com/user-attachments/assets/b10e8d8b-fe3e-4770-8ba5-e43c23f00222)
4. 输出代码已经修改为
`  for agent_return in agent.stream_chat('上海今天适合穿什么衣服'):
      print(agent_return)`

**Comment by Harold-lkk** [comment]
你可以访问 localhost:23333 这个网页么

**Comment by yangjq713** [comment]
可以访问，项目需要另外配置bing search api吗，刚刚控制台答应了信息，出现duckduck connection timeout的问题

**Comment by Harold-lkk** [comment]
这个应该是要配置一个代理 你ping不同 duckduckgo的服务

**Comment by Harold-lkk** [comment]
我们默认是duckduckgo的是一个免费的 调用bing的的一个服务
