### ISSUE TITLE
端口 8002与现有任务冲突了，如何更换端口号？

### ISSUE THREAD

**Issue by Leekinxun** [InternLM/MindSearch#37]

**Comment by datalee** [comment]
自己搜一下可以改，写死的

**Comment by Harold-lkk** [comment]
启动服务在这里可以修改
https://github.com/InternLM/MindSearch/blob/883c66c7340a9196e29a1e166a39f86bb8a17af2/mindsearch/app.py#L119

**Comment by Leekinxun** [comment]
@Harole-lkk 收到，十分感谢，请问前端的部分需要作相应的更改吗

**Comment by Harold-lkk** [comment]
> @Harole-lkk 收到，十分感谢，请问前端的部分需要作相应的更改吗

需要的，你启动那个前端可以在直接在启动的那个里边搜一下 8002 这个换成你app里边的端口号就好了
