### ISSUE TITLE
Online Demo error: format error----- SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by davinma** [InternLM/MindSearch#38]
After input and click [发送] button, the develop tools show error like this:

```
format error----- SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Dt (index-dd54c437.js:72:603814)
    at onmessage (index-dd54c437.js:72:604661)
    at index-dd54c437.js:72:594730
    at index-dd54c437.js:72:594554
    at KH (index-dd54c437.js:72:594273)
    at async x (index-dd54c437.js:72:596324)
```

when check the _**Network**_ tab, I can see that the content returned by the `https://mindsearch.openxlab.org.cn/solve` interface looks like this:

```
: ping - 2024-08-01 06:55:24.917660+00:00

: ping - 2024-08-01 06:55:39.918359+00:00

: ping - 2024-08-01 06:55:54.919023+00:00


```

No matter what I input, I always get a format error prompt. Is it because these returned contents have an incorrect format, which leads to the error mentioned in the title?

**Comment by Harold-lkk** [comment]
Sorry the service has some problem
