### ISSUE TITLE
Nodejs install await import('source-map-support').then((r) => r.default.install()) error

### ISSUE THREAD

**Issue by zhangjinnan** [InternLM/MindSearch#48]
Install MindSearch use React error as follow
```
npm start

> test-react-flow@0.0.0 start
> vite --host --mode dev

file:///root/code/MindSearch/frontend/React/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

system version，`lsb_release -a`：
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

node.js vsersion，`node -v`
```
v12.22.9
```

**Comment by zhangjinnan** [comment]
Possible Causes
Low Node.js Version: The await keyword is introduced in ES2017 (ES8) and requires Node.js 8.10.0 or higher to support. If your Node.js version is too low, this error may occur.

Module Loading Issue: The error message mentions internal/modules/esm/translators.js, indicating that Node.js encountered an issue while loading ESM (ECMAScript Modules). This could be due to improper module loading strategy or configuration.

**Comment by zhangjinnan** [comment]
1) update nodejs version to fix this iusse:
```
npm install -g n
n lts_latest
```
2)  show your nodejs version:

```
node --version
v20.16.0
```

3)  update MindSearch Recat npm and start:
```
npm install
npm start

> test-react-flow@0.0.0 start
> vite --host --mode dev


  VITE v4.5.3  ready in 304 ms

  ➜  Local:   http://localhost:8080/
  ➜  Network: http://10.5.0.55:8080/
  ➜  Network: http://198.18.0.1:8080/
  ➜  press h to show help
```

Good luck and have fun!

**Comment by zhangjinnan** [comment]
![fetch ts_error](https://github.com/user-attachments/assets/9c1cbb69-7f09-4dc2-8665-c6566ee8dde5)

**Comment by BetterSnail** [comment]
may be you can try to delete  the node_modules folder and package-lock.json; Then retry `npm install` and `npm start`
