### ISSUE TITLE
Couldn't run locally with GPT-4 model

### ISSUE THREAD

**Issue by CharryLee0426** [InternLM/MindSearch#53]
Hey developers, I followed the steps in `README.md` but couldn't run it locally. Instead, I received this error every time when I asked some question.

My Machine Specs: Windows 11 on x86 chip, 16GB RAM, CUDA installed.

What I did: pip install to install all dependencies, fill in openai api key to `mindsearch/agent/models.py`, npm install to install all front end dependencies, and run back end and front end.

```
INFO:     Started server process [389638]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
INFO:     127.0.0.1:44600 - "OPTIONS /solve HTTP/1.1" 200 OK
INFO:     127.0.0.1:44600 - "POST /solve HTTP/1.1" 200 OK
ERROR:root:Exception in sync_generator_wrapper: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "/home/charry/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/home/charry/MindSearch/mindsearch/agent/mindsearch_agent.py", line 211, in stream_chat
    for model_state, response, _ in self.llm.stream_chat(
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 157, in stream_chat
    for text in self._stream_chat(messages, **gen_params):
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 288, in streaming
    response = json.loads(decoded)
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=RuntimeError('Operation on the closed queue is forbidden')>
Traceback (most recent call last):
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/charry/MindSearch/mindsearch/app.py", line 75, in sync_generator_wrapper
    queue.sync_q.put(None)
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 371, in put
    self._parent._check_closing()
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden
INFO:     127.0.0.1:44602 - "POST /solve HTTP/1.1" 200 OK
ERROR:root:Exception in sync_generator_wrapper: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "/home/charry/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "/home/charry/MindSearch/mindsearch/agent/mindsearch_agent.py", line 211, in stream_chat
    for model_state, response, _ in self.llm.stream_chat(
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 157, in stream_chat
    for text in self._stream_chat(messages, **gen_params):
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/lagent/llms/openai.py", line 288, in streaming
    response = json.loads(decoded)
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

**Comment by Harold-lkk** [comment]
Thanks for your report, we will check out as soon as possible

**Comment by liujiangning30** [comment]
https://github.com/InternLM/lagent/pull/217

**Comment by CharryLee0426** [comment]
> [InternLM/lagent#217](https://github.com/InternLM/lagent/pull/217)

So what I need is to update the lagent package right? i'll try it. :)

**Comment by CharryLee0426** [comment]
I followed [InternLM/lagent#217](https://github.com/InternLM/lagent/pull/217) and modified this file. Then I ran it again. It still doesn't work but showed a new error.

```
INFO:     127.0.0.1:49734 - "POST /solve HTTP/1.1" 200 OK
INFO:     127.0.0.1:49742 - "POST /solve HTTP/1.1" 200 OK
ERROR:root:Exception in sync_generator_wrapper: Operation on the closed queue is forbidden
Traceback (most recent call last):
  File "/home/charry/MindSearch/mindsearch/app.py", line 69, in sync_generator_wrapper
    queue.sync_q.put(response)
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 371, in put
    self._parent._check_closing()
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=RuntimeError('Operation on the closed queue is forbidden')>
Traceback (most recent call last):
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/charry/MindSearch/mindsearch/app.py", line 75, in sync_generator_wrapper
    queue.sync_q.put(None)
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 371, in put
    self._parent._check_closing()
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden
```

**Comment by bakongi** [comment]
Hi, everyone. I'm able to run it on windows...

The core of the problem was:


JSON decode error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Problematic chunk: {
JSON decode error: Extra data: line 1 column 10 (char 9)
Problematic chunk:   "error": {
JSON decode error: Extra data: line 1 column 14 (char 13)
**Problematic chunk:     "message": "Unrecognized request argument supplied: session_id",**
JSON decode error: Extra data: line 1 column 11 (char 10)
Problematic chunk:     "type": "invalid_request_error",
JSON decode error: Extra data: line 1 column 12 (char 11)
Problematic chunk:     "param": null,
JSON decode error: Extra data: line 1 column 11 (char 10)
Problematic chunk:     "code": null
JSON decode error: Expecting value: line 1 column 3 (char 2)
Problematic chunk:   }
JSON decode error: Expecting value: line 1 column 1 (char 0)
Problematic chunk: }
response: AgentReturn(type='planner', content='', state=<AgentStatusCode.END: 0>, actions=[], response='', inner_steps=[{'role': 'user', 'content': 'Максимальная высота зданий по нормативам Казахстана'}], nodes={}, adjacency_list={}, references={}, errmsg=None)

**From Claude:**

Let's analyze the problem and propose a solution:

Error Analysis:
The error messages show that the API is returning an error response, but it's being sent in chunks. Each chunk is a valid part of a JSON object, but not a complete JSON object on its own. This is causing the JSON decoder to fail for each individual chunk.
The actual error from the API:
The API is returning an error message stating: "Unrecognized request argument supplied: session_id". This suggests that there's an issue with the request being sent to the API.
Solution:

To address this issue, we need to modify the streaming function to accumulate the chunks into a complete JSON object before parsing. Here's a revised version of the streaming function:

```
def streaming(raw_response):
    accumulated_json = ""
    for chunk in raw_response.iter_lines(chunk_size=8192, decode_unicode=False, delimiter=b'\n'):
        if chunk:
            decoded = chunk.decode('utf-8')
            print(f"Raw chunk: {decoded}")  # Log the raw chunk
            if decoded == 'data: [DONE]':
                return
            if decoded[:6] == 'data: ':
                decoded = decoded[6:]
            accumulated_json += decoded
            try:
                response = json.loads(accumulated_json)
                # Reset accumulated_json after successful parse
                accumulated_json = ""
                if 'error' in response:
                    print(f"API Error: {response['error']['message']}")
                    return
                choice = response['choices'][0]
                if choice['finish_reason'] == 'stop':
                    return
                if 'delta' in choice and 'content' in choice['delta']:
                    yield choice['delta']['content']
            except json.JSONDecodeError:
                # If it's not a complete JSON yet, continue to the next chunk
                continue
```
Addressing the API Error:
The API is complaining about an unrecognized session_id argument. You should review the gen_params dictionary in the _stream_chat method and ensure that you're not sending a session_id parameter to the API. Remove any such parameter if it exists:
```
            try:
                gen_params_new = gen_params.copy()
                # Remove session_id if it exists
                gen_params_new.pop('session_id', None)
                data = dict(
                    model=self.model_type,
                    messages=messages,
                    max_tokens=max_tokens,
                    n=1,
                    stop=gen_params_new.pop('stop_words'),
                    frequency_penalty=gen_params_new.pop('repetition_penalty'),
                    **gen_params_new,
                )
```

After this changes it starts working, but I got out of index error at some point, 

```
ERROR:root:Exception in sync_generator_wrapper: list index out of range
Traceback (most recent call last):
  File "..\MindSearch\mindsearch\app.py", line 68, in sync_generator_wrapper
    for response in agent.stream_chat(inputs):
  File "..\MindSearch\mindsearch\agent\mindsearch_agent.py", line 237, in stream_chat
    yield from self._process_code(agent_return, inner_history,
  File "..\MindSearch\mindsearch\agent\mindsearch_agent.py", line 284, in processcode
    reference, references_url = self._generate_reference(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\MindSearch\mindsearch\agent\mindsearch_agent.py", line 315, in generatereference
    ref_results = agent_return.nodes[node_name]['detail'].actions[
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

```
so I changed **mindsearch_agent.py**


```
class MindSearchAgent(BaseAgent):
    # ... (previous code remains the same)

    def _generate_reference(self, agent_return, code, as_dict):
        node_list = [
            node.strip().strip('\"') for node in re.findall(
                r'graph\.node\("((?:[^"\\]|\\.)*?)"\)', code)
        ]
        if 'add_response_node' in code:
            return self._protocol.response_prompt, dict()
        references = []
        references_url = dict()
        for node_name in node_list:
            if node_name not in agent_return.nodes:
                logger.warning(f"Node {node_name} not found in agent_return.nodes")
                continue
            
            node_detail = agent_return.nodes[node_name].get('detail')
            if not node_detail:
                logger.warning(f"No detail found for node {node_name}")
                continue

            if as_dict:
                actions = node_detail.get('actions', [])
            else:
                actions = getattr(node_detail, 'actions', [])

            if not actions:
                logger.warning(f"No actions found for node {node_name}")
                continue

            try:
                ref_results = actions[0].result[0]['content']
            except (IndexError, KeyError, AttributeError) as e:
                logger.error(f"Error accessing action result for node {node_name}: {e}")
                continue

            try:
                ref_results = json.loads(ref_results)
            except json.JSONDecodeError:
                logger.error(f"Failed to parse JSON for node {node_name}")
                continue

            ref2url = {idx: item['url'] for idx, item in ref_results.items()}
            ref = f"## {node_name}\n\n{agent_return.nodes[node_name]['response']}\n"
            updated_ref = re.sub(
                r'\[\[(\d+)\]\]',
                lambda match: f'[[{int(match.group(1)) + self.ptr}]]', ref)
            numbers = [int(n) for n in re.findall(r'\[\[(\d+)\]\]', ref)]
            if numbers:
                assert all(str(elem) in ref2url for elem in numbers)
                references_url.update({
                    str(idx + self.ptr): ref2url[str(idx)]
                    for idx in set(numbers)
                })
                self.ptr += max(numbers) + 1
            references.append(updated_ref)
        return '\n'.join(references), references_url

    # ... (rest of the class remains the same)
```
This updated version of the _generate_reference method includes several improvements:

It checks if the node exists in agent_return.nodes before trying to access it.
It checks if the detail key exists in the node before trying to access it.
It handles the difference between dictionary and object access for the as_dict case.
It checks if the actions list exists and is not empty before trying to access its elements.
It uses try-except blocks to handle potential IndexError, KeyError, or AttributeError when accessing nested data.
It adds error logging to help diagnose issues in the future. 

(Claude)

**Comment by CharryLee0426** [comment]
> Hi, everyone. I'm able to run it on windows...
> 
> The core of the problem was:
> 
> JSON decode error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1) Problematic chunk: { JSON decode error: Extra data: line 1 column 10 (char 9) Problematic chunk: "error": { JSON decode error: Extra data: line 1 column 14 (char 13) **Problematic chunk: "message": "Unrecognized request argument supplied: session_id",** JSON decode error: Extra data: line 1 column 11 (char 10) Problematic chunk: "type": "invalid_request_error", JSON decode error: Extra data: line 1 column 12 (char 11) Problematic chunk: "param": null, JSON decode error: Extra data: line 1 column 11 (char 10) Problematic chunk: "code": null JSON decode error: Expecting value: line 1 column 3 (char 2) Problematic chunk: } JSON decode error: Expecting value: line 1 column 1 (char 0) Problematic chunk: } response: AgentReturn(type='planner', content='', state=<AgentStatusCode.END: 0>, actions=[], response='', inner_steps=[{'role': 'user', 'content': 'Максимальная высота зданий по нормативам Казахстана'}], nodes={}, adjacency_list={}, references={}, errmsg=None)
> 
> **From Claude:**
> 
> Let's analyze the problem and propose a solution:
> 
> Error Analysis: The error messages show that the API is returning an error response, but it's being sent in chunks. Each chunk is a valid part of a JSON object, but not a complete JSON object on its own. This is causing the JSON decoder to fail for each individual chunk. The actual error from the API: The API is returning an error message stating: "Unrecognized request argument supplied: session_id". This suggests that there's an issue with the request being sent to the API. Solution:
> 
> To address this issue, we need to modify the streaming function to accumulate the chunks into a complete JSON object before parsing. Here's a revised version of the streaming function:
> 
> ```
> def streaming(raw_response):
>     accumulated_json = ""
>     for chunk in raw_response.iter_lines(chunk_size=8192, decode_unicode=False, delimiter=b'\n'):
>         if chunk:
>             decoded = chunk.decode('utf-8')
>             print(f"Raw chunk: {decoded}")  # Log the raw chunk
>             if decoded == 'data: [DONE]':
>                 return
>             if decoded[:6] == 'data: ':
>                 decoded = decoded[6:]
>             accumulated_json += decoded
>             try:
>                 response = json.loads(accumulated_json)
>                 # Reset accumulated_json after successful parse
>                 accumulated_json = ""
>                 if 'error' in response:
>                     print(f"API Error: {response['error']['message']}")
>                     return
>                 choice = response['choices'][0]
>                 if choice['finish_reason'] == 'stop':
>                     return
>                 if 'delta' in choice and 'content' in choice['delta']:
>                     yield choice['delta']['content']
>             except json.JSONDecodeError:
>                 # If it's not a complete JSON yet, continue to the next chunk
>                 continue
> ```
> 
> Addressing the API Error: The API is complaining about an unrecognized session_id argument. You should review the gen_params dictionary in the _stream_chat method and ensure that you're not sending a session_id parameter to the API. Remove any such parameter if it exists:
> 
> ```
>             try:
>                 gen_params_new = gen_params.copy()
>                 # Remove session_id if it exists
>                 gen_params_new.pop('session_id', None)
>                 data = dict(
>                     model=self.model_type,
>                     messages=messages,
>                     max_tokens=max_tokens,
>                     n=1,
>                     stop=gen_params_new.pop('stop_words'),
>                     frequency_penalty=gen_params_new.pop('repetition_penalty'),
>                     **gen_params_new,
>                 )
> ```
> 
> After this changes it starts working, but I got out of index error at some point,
> 
> ```
> ERROR:root:Exception in sync_generator_wrapper: list index out of range
> Traceback (most recent call last):
>   File "..\MindSearch\mindsearch\app.py", line 68, in sync_generator_wrapper
>     for response in agent.stream_chat(inputs):
>   File "..\MindSearch\mindsearch\agent\mindsearch_agent.py", line 237, in stream_chat
>     yield from self._process_code(agent_return, inner_history,
>   File "..\MindSearch\mindsearch\agent\mindsearch_agent.py", line 284, in processcode
>     reference, references_url = self._generate_reference(
>                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "..\MindSearch\mindsearch\agent\mindsearch_agent.py", line 315, in generatereference
>     ref_results = agent_return.nodes[node_name]['detail'].actions[
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> IndexError: list index out of range
> ```
> 
> so I changed **mindsearch_agent.py**
> 
> ```
> class MindSearchAgent(BaseAgent):
>     # ... (previous code remains the same)
> 
>     def _generate_reference(self, agent_return, code, as_dict):
>         node_list = [
>             node.strip().strip('\"') for node in re.findall(
>                 r'graph\.node\("((?:[^"\\]|\\.)*?)"\)', code)
>         ]
>         if 'add_response_node' in code:
>             return self._protocol.response_prompt, dict()
>         references = []
>         references_url = dict()
>         for node_name in node_list:
>             if node_name not in agent_return.nodes:
>                 logger.warning(f"Node {node_name} not found in agent_return.nodes")
>                 continue
>             
>             node_detail = agent_return.nodes[node_name].get('detail')
>             if not node_detail:
>                 logger.warning(f"No detail found for node {node_name}")
>                 continue
> 
>             if as_dict:
>                 actions = node_detail.get('actions', [])
>             else:
>                 actions = getattr(node_detail, 'actions', [])
> 
>             if not actions:
>                 logger.warning(f"No actions found for node {node_name}")
>                 continue
> 
>             try:
>                 ref_results = actions[0].result[0]['content']
>             except (IndexError, KeyError, AttributeError) as e:
>                 logger.error(f"Error accessing action result for node {node_name}: {e}")
>                 continue
> 
>             try:
>                 ref_results = json.loads(ref_results)
>             except json.JSONDecodeError:
>                 logger.error(f"Failed to parse JSON for node {node_name}")
>                 continue
> 
>             ref2url = {idx: item['url'] for idx, item in ref_results.items()}
>             ref = f"## {node_name}\n\n{agent_return.nodes[node_name]['response']}\n"
>             updated_ref = re.sub(
>                 r'\[\[(\d+)\]\]',
>                 lambda match: f'[[{int(match.group(1)) + self.ptr}]]', ref)
>             numbers = [int(n) for n in re.findall(r'\[\[(\d+)\]\]', ref)]
>             if numbers:
>                 assert all(str(elem) in ref2url for elem in numbers)
>                 references_url.update({
>                     str(idx + self.ptr): ref2url[str(idx)]
>                     for idx in set(numbers)
>                 })
>                 self.ptr += max(numbers) + 1
>             references.append(updated_ref)
>         return '\n'.join(references), references_url
> 
>     # ... (rest of the class remains the same)
> ```
> 
> This updated version of the _generate_reference method includes several improvements:
> 
> It checks if the node exists in agent_return.nodes before trying to access it. It checks if the detail key exists in the node before trying to access it. It handles the difference between dictionary and object access for the as_dict case. It checks if the actions list exists and is not empty before trying to access its elements. It uses try-except blocks to handle potential IndexError, KeyError, or AttributeError when accessing nested data. It adds error logging to help diagnose issues in the future.
> 
> (Claude)
> 
> Now it seems to work

Your solution seems good. However, can you give us the location of first `steaming_function` and `try` part? I can't find steaming function in `frontend/React` and I can't find where to add the `try` part.

Thank you!

**Comment by bakongi** [comment]
All changes made in the python files. I use streamlit client

**Comment by CharryLee0426** [comment]
Sorry, it doesn't work. I think the steaming function is in `openai.py`, but I can't find the part can match `try` part. And I changed `mindsearchAgent.py`.

**Comment by CharryLee0426** [comment]
```
Raw chunk: data: {"id":"chatcmpl-9s4dXHw8V61sYVO51AAXZn6s8ggWX","object":"chat.completion.chunk","created":1722674563,"model":"gpt-4-turbo-2024-04-09","system_fingerprint":"fp_3a6486a98f","choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":null}]}
Raw chunk: data: {"id":"chatcmpl-9s4dXHw8V61sYVO51AAXZn6s8ggWX","object":"chat.completion.chunk","created":1722674563,"model":"gpt-4-turbo-2024-04-09","system_fingerprint":"fp_3a6486a98f","choices":[{"index":0,"delta":{"content":"To"},"logprobs":null,"finish_reason":null}]}
ERROR:root:Exception in sync_generator_wrapper: Operation on the closed queue is forbidden
Traceback (most recent call last):
  File "/home/charry/MindSearch/mindsearch/app.py", line 69, in sync_generator_wrapper
    queue.sync_q.put(response)
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 371, in put
    self._parent._check_closing()
  File "/home/charry/miniconda3/envs/mindsearch/lib/python3.10/site-packages/janus/__init__.py", line 269, in _check_closing
    raise RuntimeError("Operation on the closed queue is forbidden")
RuntimeError: Operation on the closed queue is forbidden
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=RuntimeError('Operation on the closed queue is forbidden')>
```

**Comment by CharryLee0426** [comment]
Can you share your all `openai.py` file? Thank you.

**Comment by CharryLee0426** [comment]
Update. It worked for me. @bakongi is correct. What I want to add is that `openai.py` has to be the version at pull request 217. Newer versions changed a lot so that this change doesn't work.

**Comment by MyraBaba** [comment]
@CharryLee0426  @bakongi 

is there any working version that we directly get from mindSearch repo as clone git ? 

too many changes different files and messing around easily.


Best
