### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by watch-activity** [InternLM/MindSearch#56]
After starting the MindSearch API server, I asked a question on the Gradio front end, but after the MindSearch API response, the server address changed and I got the message "Read timed out" on the Gradio side.
http://0.0.0.0:8002 -> http://0.0.0.0:23333

The same applies if I use Streamlit.
How do I use it?

**Comment by Harold-lkk** [comment]
http://0.0.0.0:23333/ this is LLM server IP
http://0.0.0.0:8002/ this is MindSearch server IP

**Comment by watch-activity** [comment]
thank you for your reply.
I know the server name.
But how do I deal with the problem of it not responding?

Same thing happens if I change the timeout from 20 seconds to 60 seconds.
`requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8002): Read timed out. (read timeout=60)`

**Comment by liujiangning30** [comment]
The MindSearch service loads the model first on the first request, which can potentially cause a gradio/streamlit timeout. You can click `Clear History` or refresh the page and start from a new request.

**Comment by watch-activity** [comment]
Thank you for your reply.
Even if I press the refresh or clear history button, the connection times out.
The API server port changes automatically on the first inquiry, making it impossible to connect.

**Comment by watch-activity** [comment]
I tried React, Gradio, Streamlit, and dockerfile, but none of them worked properly.
Could you please fix it so that it works properly?

**Comment by Harold-lkk** [comment]
We don't find the error in our enviroment

**Comment by watch-activity** [comment]
Thank you for your reply.
The reason why the Issues section is flooded with error questions in such a short period of time is because it only works in your environment.
Even in the demo, the code didn't work properly, so I literally wasted my time.
