### ISSUE TITLE
ERROR: No matching distribution found for lmdeploy

### ISSUE THREAD

**Issue by fansOnly** [InternLM/MindSearch#57]
lmdeploy 这个包一直安装不了，0.2.3 或者 0.5.2 都不行。requirements.txt 里面版本去掉也不行！！！

➜   pip install -r requirements.txt 
Collecting git+https://github.com/InternLM/lagent.git (from -r requirements.txt (line 4))
  Cloning https://github.com/InternLM/lagent.git to /private/var/folders/15/15v9kxln1jv1ndj5v6x4h_6h0000gn/T/pip-req-build-yyxvmwp8
  Running command git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git /private/var/folders/15/15v9kxln1jv1ndj5v6x4h_6h0000gn/T/pip-req-build-yyxvmwp8
  Resolved https://github.com/InternLM/lagent.git to commit 47f866176b7a238f44c80ecbc0649050c52f6914
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: duckduckgo_search==5.3.1b1 in /Users/fansonly/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (5.3.1b1)
Collecting einops (from -r requirements.txt (line 2))
  Using cached einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Collecting fastapi (from -r requirements.txt (line 3))
  Using cached fastapi-0.111.1-py3-none-any.whl.metadata (26 kB)
Collecting gradio (from -r requirements.txt (line 5))
  Using cached gradio-4.40.0-py3-none-any.whl.metadata (15 kB)
Collecting janus (from -r requirements.txt (line 6))
  Using cached janus-1.0.0-py3-none-any.whl.metadata (4.5 kB)
ERROR: Could not find a version that satisfies the requirement lmdeploy (from versions: none)
ERROR: No matching distribution found for lmdeploy
➜   python --version               
Python 3.12.3

**Comment by Harold-lkk** [comment]
那要不然你装一个低版本的Python吧 这个版本太高了 LMDeploy可能还不支持

**Comment by fansOnly** [comment]
大概是多少版本合适，我换到3.8.19也不行

➜   pip install -r requirements.txt
Collecting git+https://github.com/InternLM/lagent.git (from -r requirements.txt (line 4))
  Cloning https://github.com/InternLM/lagent.git to /private/var/folders/15/15v9kxln1jv1ndj5v6x4h_6h0000gn/T/pip-req-build-mdn1is57
  Running command git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git /private/var/folders/15/15v9kxln1jv1ndj5v6x4h_6h0000gn/T/pip-req-build-mdn1is57
  Resolved https://github.com/InternLM/lagent.git to commit 34284d75cac184757cd1bdc492fd000f96db3195
  Preparing metadata (setup.py) ... done
Collecting duckduckgo_search==5.3.1b1
  Using cached duckduckgo_search-5.3.1b1-py3-none-any.whl (23 kB)
Collecting einops
  Using cached einops-0.8.0-py3-none-any.whl (43 kB)
Collecting fastapi
  Using cached fastapi-0.111.1-py3-none-any.whl (92 kB)
Collecting gradio
  Using cached gradio-4.40.0-py3-none-any.whl (12.5 MB)
Collecting janus
  Using cached janus-1.0.0-py3-none-any.whl (6.9 kB)
ERROR: Could not find a version that satisfies the requirement lmdeploy==0.2.3 (from versions: none)
ERROR: No matching distribution found for lmdeploy==0.2.3

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
➜   python --version               
Python 3.8.19

**Comment by liujiangning30** [comment]
Python 3.10.0 is ok

**Comment by CharryLee0426** [comment]
Python 3.9 and Python 3.10 are Okay via my test. But still can't work.

**Comment by fansOnly** [comment]
I tried 3.9.0 and 3.10.0, both returned the same error as before and the installation still failed

**Comment by Harold-lkk** [comment]
Try to use lmdeploy==0.4.0

**Comment by Harold-lkk** [comment]
> Python 3.9 and Python 3.10 are Okay via my test. But still can't work.

What is the problem?

**Comment by CharryLee0426** [comment]
> > Python 3.9 and Python 3.10 are Okay via my test. But still can't work.
> 
> What is the problem?

See this Issue [Issue53](https://github.com/InternLM/MindSearch/issues/53)

**Comment by fansOnly** [comment]
> Try to use lmdeploy==0.4.0

I have tried various methods, Python 3.8+ and lmdeploy 0.2.3,0.4.0,0.5.2, but none of them seem to work. I wonder if it has something to do with the computer system version?

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15

**Comment by lvhan028** [comment]
LMDeploy doesn't support MacOS
It is an inference framework developed on CUDA platform

**Comment by fansOnly** [comment]
> LMDeploy doesn't support MacOS It is an inference framework developed on CUDA platform

got it!
thank you!

**Comment by VersaceXcodes** [comment]
so whats the solution?

**Comment by crazygo** [comment]
借楼追问，我的是Python 3.10.14，同样无法安装
(v310)➜  MindSearch git:(main) pip install lmdeploy
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement lmdeploy (from versions: none)
ERROR: No matching distribution found for lmdeploy

**Comment by alesaccoia** [comment]
Solution is to remove the dependency as long as one uses GPT-4
