### ISSUE TITLE
希望能够提供一个完整的docker镜像

### ISSUE THREAD

**Issue by darkelfzdy** [InternLM/MindSearch#58]
希望能够提供一个完整的docker镜像，方便自部署

**Comment by Harold-lkk** [comment]
https://github.com/InternLM/MindSearch/blob/main/Dockerfile

**Comment by MyraBaba** [comment]
@Harold-lkk 

Can you also provide dockerfile for AI backend so we can run  

python -m mindsearch.app --lang en --model_format internlm_server

command corectly without any missed dependency or version conflict ?
