### ISSUE TITLE
运行terminal.py之后，报错code

### ISSUE THREAD

**Issue by WangXuCh** [InternLM/MindSearch#62]
Traceback (most recent call last):
  File "terminal.py", line 49, in <module>
    for agent_return in agent.stream_chat('上海今天适合穿什么衣服'):
  File "mindsearch_agent.py", line 239, in stream_chat
    if code:
UnboundLocalError: local variable 'code' referenced before assignment

**Comment by liujiangning30** [comment]
https://github.com/InternLM/MindSearch/issues/40

**Comment by WangXuCh** [comment]
没用，我用的模型就是2.5_7b_chat，然后后面那个人说的那个提前定义code为none，我试了一下，这样不会有输出

**Comment by ydniuyongjie** [comment]
问题解决了？






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年8月8日 11:52 |
| 收件人 | ***@***.***> |
| 抄送人 | Tom ***@***.***>,
***@***.***> |
| 主题 | Re: [InternLM/MindSearch] 运行terminal.py之后，报错code (Issue #62) |

Closed #62 as completed.
