### ISSUE TITLE
Error installing requirements.txt

### ISSUE THREAD

**Issue by Androidew** [InternLM/MindSearch#64]
I've been trying to run `pip install -r requirements.txt` but get the error:

> ERROR: Could not find a version that satisfies the requirement triton<2.2.0,>=2.1.0 (from lmdeploy) (from versions: none)
> ERROR: No matching distribution found for triton<2.2.0,>=2.1.0

**Comment by nonew** [comment]
I have same issue.

**Comment by Harold-lkk** [comment]
LMDeploy is not supported on MacOS. Also, the high Python version does not support the low lmdeploy version and we will test higher lmdeploy version as soon as possible

**Comment by ssrheart425** [comment]
我也是这个问题，目前有什么好的解决办法吗，我的python是3.10.7版本

**Comment by ssrheart425** [comment]
`pip install --upgrade lmdeploy` 我执行完这个之后，报错`PS D:\MindSearch-main> pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/InternLM/lagent.git (from -r requirements.txt (line 4))
  Cloning https://github.com/InternLM/lagent.git to c:\users\heart\appdata\local\temp\pip-req-build-arxjayxn
  Running command git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git 'C:\Users\heart\AppData\Local\Temp\pip-req-build-arxjayxn'
  error: RPC failed; curl 28 Recv failure: Connection was reset
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git 'C:\Users\heart\AppData\Local\Temp\pip-req-build-arxjayxn' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git 'C:\Users\heart\AppData\Local\Temp\pip-req-build-arxjayxn' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS D:\MindSearch-main> pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/InternLM/lagent.git (from -r requirements.txt (line 4))
  Cloning https://github.com/InternLM/lagent.git to c:\users\heart\appdata\local\temp\pip-req-build-lbwq9dv_
  Running command git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git 'C:\Users\heart\AppData\Local\Temp\pip-req-build-lbwq9dv_'
  fatal: unable to access 'https://github.com/InternLM/lagent.git/': Failed to connect to github.com port 443 after 21070 ms: Couldn't connect to server
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git 'C:\Users\heart\AppData\Local\Temp\pip-req-build-lbwq9dv_' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/InternLM/lagent.git 'C:\Users\heart\AppData\Local\Temp\pip-req-build-lbwq9dv_' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.` 麻烦看一下

**Comment by liujiangning30** [comment]
https://github.com/InternLM/MindSearch/pull/94
