### ISSUE TITLE
anyone succesfully ran on ubuntu 22.04 ?

### ISSUE THREAD

**Issue by MyraBaba** [InternLM/MindSearch#65]
ubuntu 22.04 Quadro RTX 5000 16G

still struggling  vanilla setup run. It makes a huge friction to start.

**Comment by Harold-lkk** [comment]
What issue are you encountering?

**Comment by XYZliang** [comment]
I easily run on Ubuntu24. Why not specify your exact issue?

**Comment by MyraBaba** [comment]
except local model its working now.
