### ISSUE TITLE
用qwen运行之后，报错

### ISSUE THREAD

**Issue by ranwithyou** [InternLM/MindSearch#66]
ERROR:mindsearch.agent.mindsearch_agent:Error executing code:  Traceback (most recent call last):   File "/root/MindSearch/mindsearch/agent/mindsearch_agent.py", line 350, in run_command     assert plan_graph is not None AssertionError ERROR:root:Exception in sync_generator_wrapper: 'NoneType' object has no attribute 'searcher_resp_queue' Traceback (most recent call last):   File "/root/MindSearch/mindsearch/app.py", line 68, in sync_generator_wrapper     for response in agent.stream_chat(inputs):   File "/root/MindSearch/mindsearch/agent/mindsearch_agent.py", line 237, in stream_chat     yield from self._process_code(agent_return, inner_history,   File "/root/MindSearch/mindsearch/agent/mindsearch_agent.py", line 261, in _process_code     for node_name, node, adj in self.execute_code(   File "/root/MindSearch/mindsearch/agent/mindsearch_agent.py", line 369, in execute_code     item = self.local_dict.get('graph').searcher_resp_queue.get( AttributeError: 'NoneType' object has no attribute 'searcher_resp_queue'

**Comment by liujiangning30** [comment]
https://github.com/InternLM/lagent/pull/225
https://github.com/InternLM/MindSearch/pull/91
AND You may need to optimize the fewshot so that it follows the response protocol.

**Comment by huanglan513** [comment]
换成qwen_max好像就不报这个错
