### ISSUE TITLE
"In the Readme.md, the Chinese value for the 'lang' option should not be 'zh', but 'cn', refer to the code in mindsearch/app.py

### ISSUE THREAD

**Issue by leagend** [InternLM/MindSearch#67]
in https://github.com/InternLM/MindSearch/blob/main/mindsearch/app.py#L21
`   
 parser.add_argument('--lang', default='cn', type=str, help='Language')
`

while in Readme.md, it says "--lang: language of the model, en for English and zh for Chinese."

**Comment by Harold-lkk** [comment]
Thanks for your report. Can your pull a request to fix it?

**Comment by leagend** [comment]
I think this open PR will fix it.
https://github.com/InternLM/MindSearch/pull/70
