### ISSUE TITLE
[TM][WARNING] [RejectInvalidRequests] Skipping invalid infer request for id 302726, code = 6

### ISSUE THREAD

**Issue by LuckFXY** [InternLM/MindSearch#72]
Just run the mindSearch.app according to the README, and I always get the above error message in the server when I send any message from the web UI monitored by the NPM server.

**Comment by Harold-lkk** [comment]
This is a warning, not an error. Do you run successfully?

**Comment by zhtgyx** [comment]
I also encountered the same problem. After waiting, there was no response or result output on the page. Why is this?
