### ISSUE TITLE
前端输出吐字慢

### ISSUE THREAD

**Issue by vansin** [InternLM/MindSearch#81]
越到后面前端吐字越慢，及其影响体验～

![img_v3_02dd_87dc3efb-28dc-4fc3-8d91-7006ad99716g](https://github.com/user-attachments/assets/bd4905c2-1d1f-4f9a-80cd-2537dfa45e54)

深度体验了两天 MindSearch 开源前端吐字特别慢，后端3秒就推理完反馈给前端了，前端输出要一个字一个字吐出要等 10分钟，及其影响体验～。

react、gradio 版本都有这个问题，streamlit还没有尝试

**Comment by datalee** [comment]
前段会阻塞，有时候后端跑完了，前端还卡着
