### ISSUE TITLE
Let's all find examples of good/bad usage.(大家一起记录优秀/不好的示例)

### ISSUE THREAD

**Issue by Harold-lkk** [InternLM/MindSearch#88]
The interface and design of Mindsearch offer a fresh take compared to traditional search engines. As you explore its features, you'll likely come across some standout use cases that really impress. However, you might also encounter a few areas where it doesn't quite meet expectations. Let's take note of these experiences and discuss them together.

MindSearch 的设计和交互方式可能对比现有搜索引擎的比较新颖，在使用过程中，可能会发现一些令人眼前一亮的使用案例，也会遇到一些表现不尽人意的情况，让我们记录一下吧，大家一块探讨。

**Comment by wbbeyourself** [comment]
![image](https://github.com/user-attachments/assets/b2d89092-3ac6-4c2c-adce-b58bf3e0ecba)

**Comment by datalee** [comment]
咨询个问题：如果领域内使用的话，发现第一步问题拆解对实体的认知有偏差，如果干预这个阶段的问题拆解？

**Comment by Harold-lkk** [comment]
> 咨询个问题：如果领域内使用的话，发现第一步问题拆解对实体的认知有偏差，如果干预这个阶段的问题拆解？

现在的实现还不支持，如果想实现的话可以对每一个步骤后续都接入一个反馈或者手动调整节点确认后在去执行子节点

**Comment by datalee** [comment]
> > 咨询个问题：如果领域内使用的话，发现第一步问题拆解对实体的认知有偏差，如果干预这个阶段的问题拆解？
> 
> 现在的实现还不支持，如果想实现的话可以对每一个步骤后续都接入一个反馈或者手动调整节点确认后在去执行子节点

期待有个case可以指导下怎么搞

**Comment by datalee** [comment]
为了准确回答如何在泰山v2服务器的BIOS界面中查看硬盘信息，需要明确查询的具体步骤和可能的关键词。这包括了解泰山v2服务器的BIOS界面布局、硬盘信息的显示位置以及具体的查看方法。通过这些关键词，可以获取详细的指南或教程。
```json
{
    "name": "BingBrowser.search",
    "parameters": {
        "query": [
            "泰山v2服务器 BIOS 硬盘信息查看步骤",
            "泰山v2服务器 BIOS 如何显示硬盘信息",
            "泰山v2服务器 BIOS 硬盘信息查询方法",
            "泰山v2服务器 BIOS 硬盘信息查看教程"
        ]
    }
}
```
另外，请教下这一块的代码是在哪里实现的：对搜索结果的react

**Comment by liujiangning30** [comment]
> 为了在xxx服务器的BIOS界面中查看硬盘信息，我需要寻找具体介绍xxx服务器BIOS界面操作和硬盘信息查看方法的网页。以下是我的分析和选择过程：
> 
> 1. **网页0**：该网页主要讨论了xxxx操作。
> 2. **网页1**：该网页主要讨论了xxx无关。
> 3. **网页2**：该网页主要讨论了xxxx操作。
> 4. **网页3**：该网页主要讨论了xxxx无关。
> 5. **网页4**：该网页主要讨论了xxxx操作。
> 
> 综上所述，网页3《xxxx》可能包含xxx服务器的BIOS界面操作信息，因此我选择打开该网页进行进一步阅读。
> 
> ```json
> {
>     "name": "BingBrowser.select",
>     "parameters": {
>         "select_ids": [
>             10
>         ]
>     }
> }
> ```
> 
> 另外，请教下这一块的代码是在哪里实现的：对搜索结果的react

https://github.com/InternLM/lagent/blob/a8ae3872fac6e23f832d860131a1196f1a722fe1/lagent/actions/bing_browser.py#L232

**Comment by leonall** [comment]
总-分-总，耗时太长了，得到的总结很笼统

**Comment by kShines** [comment]
使用 internlm_silicon作为模型时，总是报这个错误，我看请求的结果也是200，这大概是什么原因，lagent/llms/openai.py", line 296, in streaming
    yield choice['delta']['content']
KeyError: 'content'

**Comment by chuanzhubin** [comment]
如何搜索本地文档库？
