### ISSUE TITLE
执行命令python -m mindsearch.app --lang en --model_format internlm_server一直在下载模型文件正常么？

### ISSUE THREAD

**Issue by sunshineywz123** [InternLM/MindSearch#93]
执行命令python -m mindsearch.app --lang en --model_format internlm_server一直在下载模型文件正常么？

model-00002-of-00008.safetensors:  74%|██▏| 1.45G/1.95G [2:44:39<28:20, 294kB/s]

model-00005-of-00008.safetensors:  66%|█▉ | 1.30G/1.98G [2:36:31<38:17, 296kB/s]
model-00005-of-00008.safetensors:  73%|██▏| 1.45G/1.98G [2:44:52<30:02, 296kB/s]
model-00007-of-00008.safetensors:  49%|▉ | 965M/1.98G [2:44:46<1:26:49, 195kB/s]
model-00008-of-00008.safetensors:  55%|█ | 965M/1.75G [2:44:49<1:05:26, 200kB/s]

**Comment by Harold-lkk** [comment]
正常的 这个是从HF上下载模型
