### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by ydniuyongjie** [InternLM/MindSearch#99]
运行 python -m mindsearch.app --lang en --model_format internlm_server
出现：self.client = lmdeploy.serve(
                  ^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable 错误

**Comment by liujiangning30** [comment]
能贴一下完整的日志吗？

**Comment by ydniuyongjie** [comment]
从哪里可以看到日志？








---- Replied Message ----
| From | ***@***.***> |
| Date | 8/6/2024 10:21 |
| To | ***@***.***> |
| Cc | Tom ***@***.***>,
***@***.***> |
| Subject | Re: [InternLM/MindSearch] TypeError: 'module' object is not callable (Issue #99) |

能贴一下完整的日志吗？

**Comment by liujiangning30** [comment]
终端只打印了你贴的日志？

**Comment by ydniuyongjie** [comment]
我看了提示，好像是找不到CUDA，可能是因为我的计算机不支持CUDA的原因吧。






---- Replied Message ----
| From | ***@***.***> |
| Date | 8/6/2024 10:52 |
| To | ***@***.***> |
| Cc | Tom ***@***.***>,
***@***.***> |
| Subject | Re: [InternLM/MindSearch] TypeError: 'module' object is not callable (Issue #99) |

终端只打印了你贴的日志？
